# Don't change this! Version used to track needed updates.
version = 0

# Scrolls up a 'page' in the Config GUI

[pageUp]
ctrl = "default"
shift = "default"
alt = "default"
type = "keyboard"
key = 266

# Scrolls down a 'page' in the Config GUI

[pageDown]
ctrl = "default"
shift = "default"
alt = "default"
type = "keyboard"
key = 267

# Scrolls to the top of the Config GUI

[home]
ctrl = "default"
shift = "default"
alt = "default"
type = "keyboard"
key = 268

# Scrolls to the bottom of the Config GUI

[end]
ctrl = "default"
shift = "default"
alt = "default"
type = "keyboard"
key = 269

# Copies the currently hovered or focused config setting

[copy]
ctrl = "true"
shift = "false"
alt = "false"
type = "keyboard"
key = 67

# Pastes the last-copied setting into a compatible new setting

[paste]
ctrl = "true"
shift = "false"
alt = "false"
type = "keyboard"
key = 86

# Not currently used by Fzzy Config - cuts the selected information to a copy buffer

[cut]
ctrl = "true"
shift = "false"
alt = "false"
type = "keyboard"
key = 88

# Saves changes made to the current Config and sends updates to the server

[save]
ctrl = "true"
shift = "false"
alt = "false"
type = "keyboard"
key = 83

# Undos changes made from newest to oldest change

[undo]
ctrl = "true"
shift = "false"
alt = "false"
type = "keyboard"
key = 90

# Opens the context menu for the currently hovered or selected element

[contextMouse]
ctrl = "default"
shift = "default"
alt = "default"
type = "mouse"
key = 1

# Backs out to the previous config screen

[back]
ctrl = "default"
shift = "default"
alt = "default"
type = "keyboard"
key = 259

# Opens the 'Go-To' menu (Not used to focus the search bar)

[search]
ctrl = "true"
shift = "false"
alt = "false"
type = "keyboard"
key = 69

# Opens the GUI info menu

[info]
ctrl = "default"
shift = "default"
alt = "default"
type = "keyboard"
key = 290

# Fully exits all open config GUIs (and saves them as applicable)

[fullExit]
ctrl = "false"
shift = "true"
alt = "false"
type = "keyboard"
key = 256

# Focuses the Config GUI search bar

[[find]]
ctrl = "true"
shift = "false"
alt = "false"
type = "keyboard"
key = 70

[[find]]
ctrl = "false"
shift = "false"
alt = "false"
type = "keyboard"
key = 292

# Opens the context menu for the currently hovered or selected element

[[contextKeyboard]]
ctrl = "false"
shift = "true"
alt = "false"
type = "keyboard"
key = 299

[[contextKeyboard]]
ctrl = "false"
shift = "false"
alt = "false"
type = "keyboard"
key = 348

# Not currently used by Fzzy Config - A universal 'Enter' keybind

[[act]]
ctrl = "false"
shift = "false"
alt = "false"
type = "keyboard"
key = 257

[[act]]
ctrl = "false"
shift = "false"
alt = "false"
type = "keyboard"
key = 335