
#General mod settings
[general]
	#If true, optimizes the expensive zombie village raid task that scans around a lot for villagers, by default cuts the chance to 1/3
	optimizationZombieVillageRaid = true
	#If true, optimizes the expensive mob targeting tasks
	optimizationMobEnemyTargeting = true
	#If true, optimizes the expensive mob wander pathfinding, even more so if far from players
	optimizationMobWandering = true
	#If true, disables the frequent pathfinds done while already following a path
	optimizationMobRepathfinding = true
	#If true, optimizes the expensive searching done to find a turtle egg to crush, for zombies/husks, by default fully disabling it
	optimizationZombieSearchAndDestroyTurtleEgg = true
	#If true, disables the expensive 3x3x3 hazard scanning that is constantly running every tick while path following, for monsters only, your pets are safe
	optimizationMonsterHazardAvoidingPathfollowing = true
	#If true, wander pathfinding and enemy targeting attempts will be further reduced when far away from players
	playerProximityReducedRate = true

