//此文件提供铁魔法系列修改
ServerEvents.recipes(event => {
    //修改背包配方
    event.remove({id:'sophisticatedbackpacks:backpack'})
    event.shaped(Item.of('sophisticatedbackpacks:backpack',1),
        ['BAB',
        'BCB',
        'DED'],
        {
            A:'#forge:leather',
            B:'#forge:string',
            C:'#balm:wooden_chests',
            D:'irons_spellbooks:magic_cloth',
            E:'create:andesite_alloy'
        }
    )
    
    //修改奥术布匹配方
    event.replaceInput({mod:'irons_spellbooks',output:'irons_spellbooks:magic_cloth'},
    '#minecraft:wool', 'immersiveengineering:hemp_fabric' )

    //修改木质法杖配方
    event.remove({id:'irons_spellbooks:graybeard_staff'})
    event.shaped(Item.of('irons_spellbooks:graybeard_staff',1),
        ['  A',
        ' B ',
        'C  '],
        {
            A:'irons_spellbooks:arcane_essence',
            B:'kubejs:bronze_shovel',
            C:'#forge:ingots'
        }
    )

    //修改法师护甲配方
    event.remove({id:'irons_spellbooks:wandering_magician_helmet'})
    event.remove({id:'irons_spellbooks:wandering_magician_chestplate'})
    event.remove({id:'irons_spellbooks:wandering_magician_leggings'})
    event.remove({id:'irons_spellbooks:wandering_magician_boots'})
    event.shaped(Item.of('irons_spellbooks:wandering_magician_helmet',1),
        ['AAA',
        'ABA'],
        {
            A:'irons_spellbooks:magic_cloth',
            B:'#forge:ingots/copper'
        }
    )
    event.shaped(Item.of('irons_spellbooks:wandering_magician_chestplate',1),
        ['ABA',
        'AAA',
        'AAA'],
        {
            A:'irons_spellbooks:magic_cloth',
            B:'#forge:ingots/copper'
        }
    )
    event.shaped(Item.of('irons_spellbooks:wandering_magician_leggings',1),
        ['AAA',
        'ABA',
        'A A'],
        {
            A:'irons_spellbooks:magic_cloth',
            B:'#forge:ingots/copper'
        }
    )
    event.shaped(Item.of('irons_spellbooks:wandering_magician_boots',1),
        ['A A',
        'ABA'],
        {
            A:'irons_spellbooks:magic_cloth',
            B:'#forge:ingots/copper'
        }
    )

    //修改法术书系列配方
    event.remove({id:'irons_spellbooks:iron_spell_book'})
    event.remove({id:'irons_spellbooks:gold_spell_book'})
    event.remove({id:'irons_spellbooks:diamond_spell_book'})
    event.shaped(Item.of('irons_spellbooks:iron_spell_book',1),
        ['ABB',
        'ACD',
        'ABB'],
        {
            A:'minecraft:chain',
            B:'#forge:leather',
            C:'irons_spellbooks:copper_spell_book',
            D:'minecraft:paper'
        }
    )
    event.shaped(Item.of('irons_spellbooks:gold_spell_book',1),
        ['ABB',
        'ACD',
        'ABB'],
        {
            A:'#forge:ingots/brass',
            B:'#forge:leather',
            C:'irons_spellbooks:iron_spell_book',
            D:'irons_spellbooks:arcane_ingot'
        }
    )
    event.shaped(Item.of('irons_spellbooks:diamond_spell_book',1),
        ['ABB',
        'ACD',
        'ABB'],
        {
            A:'botania:mana_diamond',
            B:'irons_spellbooks:hogskin',
            C:'irons_spellbooks:gold_spell_book',
            D:'bloodmagic:apprenticebloodorb'
        }
    )

    //修改传说法术书配方
    event.replaceInput({mod:'irons_spellbooks',output:'irons_spellbooks:netherite_spell_book'},
    'irons_spellbooks:lightning_bottle', 'botania:terrasteel_ingot' )
    event.replaceInput({mod:'irons_spellbooks',output:'irons_spellbooks:dragonskin_spell_book'},
    'minecraft:obsidian', 'botania:terrasteel_ingot' )

    //奥术铁砧配方重写
    event.remove({id:'irons_spellbooks:arcane_anvil'})
    event.shaped(Item.of('irons_spellbooks:arcane_anvil',1),
        ['ABA',
        ' C ',
        'EDE'],
        {
            A:'botania:manasteel_block',
            B:'minecraft:amethyst_block',
            C:'botania:terrasteel_ingot',
            D:'#minecraft:anvil',
            E:'undergarden:cloggrum_block'
        }
    )

    //泰拉钢锭加入各系胸甲配方
    event.remove({id:'irons_spellbooks:cryomancer_chestplate'})
    event.shaped(Item.of('irons_spellbooks:cryomancer_chestplate',1),
        ['ABA',
        'ACA',
        'AAA'],
        {
            A:'irons_spellbooks:magic_cloth',
            B:'irons_spellbooks:ice_rune',
            C:'botania:terrasteel_ingot'
        }
    )
    event.remove({id:'irons_spellbooks:pyromancer_chestplate'})
    event.shaped(Item.of('irons_spellbooks:pyromancer_chestplate',1),
        ['ABA',
        'ACA',
        'AAA'],
        {
            A:'irons_spellbooks:magic_cloth',
            B:'irons_spellbooks:fire_rune',
            C:'botania:terrasteel_ingot'
        }
    )
    event.remove({id:'irons_spellbooks:priest_chestplate'})
    event.shaped(Item.of('irons_spellbooks:priest_chestplate',1),
        ['ABA',
        'ACA',
        'AAA'],
        {
            A:'irons_spellbooks:magic_cloth',
            B:'irons_spellbooks:holy_rune',
            C:'botania:terrasteel_ingot'
        }
    )
    event.remove({id:'irons_spellbooks:electromancer_chestplate'})
    event.shaped(Item.of('irons_spellbooks:electromancer_chestplate',1),
        ['ABA',
        'ACA',
        'AAA'],
        {
            A:'irons_spellbooks:magic_cloth',
            B:'irons_spellbooks:lightning_rune',
            C:'botania:terrasteel_ingot'
        }
    )
    event.remove({id:'irons_spellbooks:archevoker_chestplate'})
    event.shaped(Item.of('irons_spellbooks:archevoker_chestplate',1),
        ['ABA',
        'ACA',
        'AAA'],
        {
            A:'irons_spellbooks:magic_cloth',
            B:'irons_spellbooks:evocation_rune',
            C:'botania:terrasteel_ingot'
        }
    )
    event.remove({id:'irons_spellbooks:cultist_chestplate'})
    event.shaped(Item.of('irons_spellbooks:cultist_chestplate',1),
        ['ABA',
        'ACA',
        'AAA'],
        {
            A:'irons_spellbooks:magic_cloth',
            B:'irons_spellbooks:blood_rune',
            C:'botania:terrasteel_ingot'
        }
    )
    event.remove({id:'irons_spellbooks:plagued_chestplate'})
    event.shaped(Item.of('irons_spellbooks:plagued_chestplate',1),
        ['ABA',
        'ACA',
        'AAA'],
        {
            A:'irons_spellbooks:magic_cloth',
            B:'irons_spellbooks:nature_rune',
            C:'botania:terrasteel_ingot'
        }
    )
    event.remove({id:'irons_spellbooks:shadowwalker_chestplate'})
    event.shaped(Item.of('irons_spellbooks:shadowwalker_chestplate',1),
        ['ABA',
        'ACA',
        'AAA'],
        {
            A:'irons_spellbooks:magic_cloth',
            B:'irons_spellbooks:ender_rune',
            C:'botania:terrasteel_ingot'
        }
    )

    //添加终极锭合成
    event.remove({id:'createchromaticreturn:refined_radiance_recipe'})
    event.shaped(Item.of('createchromaticreturn:refined_radiance',1),
        ['ABC',
        'DEF',
        'GHI'],
        {
            A:'irons_spellbooks:eldritch_manuscript',
            B:'irons_spellbooks:permafrost_shard',
            C:'irons_spellbooks:blood_staff',
            D:'irons_spellbooks:hither_thither_wand',
            E:'createchromaticreturn:glowing_ingot',
            F:'irons_spellbooks:tarnished_helmet',
            G:'irons_spellbooks:magehunter',
            H:'irons_spellbooks:keeper_flamberge',
            I:'irons_spellbooks:dragonskin_spell_book'
        }
    )
    event.remove({id:'createchromaticreturn:multiplite_recipe'})
    event.shaped(Item.of('createchromaticreturn:multiplite_ingot',1),
        ['ABC',
        'DEF',
        'GHI'],
        {
            A:'createchromaticreturn:glowing_ingot',
            B:'createchromaticreturn:refined_radiance',
            C:'createchromaticreturn:silkstrum',
            D:'createchromaticreturn:silkstrum_book',
            E:'createchromaticreturn:industrium_book',
            F:'createchromaticreturn:durasteel_book',
            G:'createchromaticreturn:shadow_steel',
            H:'createchromaticreturn:industrium_ingot',
            I:'createchromaticreturn:durasteel_ingot'
        }
    )
})