LootJS.modifiers((event) => {
    event.addLootTableModifier(LootType.CHEST).replaceLoot("immersiveengineering:ingot_aluminum", "copper_ingot", true)
    event.addLootTableModifier(LootType.CHEST).replaceLoot("immersiveengineering:stick_aluminum", "immersiveengineering:stick_iron", true)
    event.addLootTypeModifier(LootType.CHEST).replaceLoot("iron_ingot", "raw_iron", true)
    event.addLootTypeModifier(LootType.CHEST).replaceLoot("iron_nugget", "minecraft:copper_nugget", true)
    event.addLootTypeModifier(LootType.ENTITY).replaceLoot("iron_ingot", "raw_iron", true)
    event.addBlockLootModifier("minecraft:grass").removeLoot("minecraft:wheat_seeds")
    event.addBlockLootModifier("minecraft:tall_grass").removeLoot("minecraft:wheat_seeds")
    event.addBlockLootModifier("minecraft:grass").removeLoot("immersiveengineering:seed")
    event.addBlockLootModifier("minecraft:tall_grass").removeLoot("immersiveengineering:seed")
})
