
#General settings of Crash Assistant mod.
[general]
	#Link which will be opened in browser on request_help_button pressed.
	#If equals CHANGE_ME, will open Forge/NeoForge/Fabric/Quilt discord link. Names of communities/channels also will be used not from config, but according to this link.
	#Must start with 'https://' or 'www.'
	help_link = "https://www.mcmod.cn/modpack/826.html"
	#Anyways log will be uploaded to mclo.gs, but with this option you can wrap link to gnomebot.dev for better formatting.
	#If help_link equals 'CHANGE_ME', this value will be ignored and gnomebot.dev used.
	#Supported values: mclo.gs / gnomebot.dev
	upload_to = "gnomebot.dev"
	#Show gui on minecraft crashed on modloading and FML error screen displayed.
	show_on_fml_error_screen = true
	#Close old CrashAssistantApp if it's still running when starting a new instance of Minecraft, to avoid confusing player with window from old crash.
	kill_old_app = true
	#If options.txt doesn't exist, the default language will be used.
	default_lang = "en_us"
	#List of blacklisted log files (checked with startswith()). This files won't show in GUI logs list.
	blacklisted_logs = []
	#Before uploading the first log, requires the user to accept the privacy policy.
	#Disabling this option may be illegal in some countries if you are modpack creator. Disable at your own risk.
	enable_privacy_policy_acceptance = true

#Here you can change text of lang placeHolders.
#Also you can change any text in lang files.
#You don't need to modify jar. You can change it in config/crash_assistant/lang. For more info read README.md file located where.
[text]
	#$CONFIG.text.support_name$ in lang files will be replaced with this value.
	#For example this placeHolder used in: "Request help in the $CONFIG.text.support_name$"
	support_name = "example Discord"
	#$CONFIG.text.support_place$ in lang files will be replaced with this value.
	support_place = "#example channel"
	#$CONFIG.text.modpack_name$ in lang files will be replaced with this value.
	#For example this placeHolder used in: "Oops, $CONFIG.text.modpack_name$ crashed!"
	#Supports Better Compatibility Checker integration. You can use $BCC.modpackName$, $BCC.modpackVersion$, etc and it will be replaced with value from BCC config.
	modpack_name = "$BCC.modpackName$ $BCC.modpackVersion$"

#Settings of message generated by Upload all button
[generated_message]
	#Add ### prefix before filename.
	#This can prevent too small, hard to hit on mobile links.
	h3_prefix = true
	#If the modpack is created for a non-English-speaking audience, —Åhange this to the language the modpack is designed for.
	#This lang will be used only for generating message by "Upload all..." button.Do not modify this value if there's a chance that the generated message will be sent to English-speaking communities.
	generated_msg_lang = "en_us"
	#This text will be under "$CONFIG.text.modpack_name$ crashed!" in generated message by Upload all button.
	#You can include:
	#   * some form, which users should fill out.
	#   * additional information like Minecraft version, etc.
	text_under_crashed = ""
	#With this option you can notify user about something related with posting generated message.
	#For example if they need to fill some option from "text_under_crashed", etc.
	#Supports html formatting, placeholders.
	#Leave empty to prevent showing this warning message.
	warning_after_upload_all_button_press = ""
	#Replaces "\n" separator between logs to "   |   " to make message vertically smaller.
	one_line_logs = true
	#Adds line in log list about this Intel processor can be corrupted.
	intel_corrupted_notification = true
	#Puts problematic frame from hs_err to message.
	put_problematic_frame_to_message = true
	#Puts analysis result(names of crash reasons) to message, instead of just count.
	put_analysis_result_to_message = true
	#Color modified mods count/analysis in msg with ANSI.
	#Can be needed to be disabled if issues are reported to something not supporting ANSI codeblocks, like GitHub.
	color_message = true

#Settings of modlist feature.
#Adds in generated msg block about which mods modpack user added/removed/updated.
#Also you can see diff by running '/crash_assistant modlist diff' command.
[modpack_modlist]
	#Enable feature.
	enabled = true
	#nicknames of players, who considered as modpack creator.
	#Only this players can overwrite modlist.json
	#If this feature is enabled and this array is empty, will be appended with nickname of current player.
	modpack_creators = ["JasdewStarfield"]
	#If enabled, modlist.json will be overwritten on every launch(first tick of TitleScreen),
	#then game is launched by modpack creator.
	#So you won't forget to save it before publishing.
	#If you want to save manually: disable this and use '/crash_assistant modlist save' command.
	auto_update = true
	#If enabled, will add resourcepacks to modlist.json
	#After filename where will be ' (resourcepack)' suffix.
	add_resourcepacks = false
	#If enabled, will add modloader jar name to modlist, to easily track if user changed version of modloader.
	add_modloader_jar_name = true
	#If enabled, will add generated modlist.txt, with names of all mods / modids / mixin configs / jarjar mods info to logs.
	#
	add_modlist_txt_as_log = true

#Settings of '/crash_assistant crash' command feature.
[crash_command]
	#Enable feature.
	enabled = true
	#To ensure the user really wants to crash the game, the command needs to be run again within this amount of seconds.
	#Set to <= 0 to disable the confirmation.
	seconds = 10

[greeting]
	#You don't need to touch this option.
	#On first world join of modpack creator if set to false shows greeting, then self enables.
	shown_greeting = true

#Settings of notifying about intel corrupted processors.
[intel_corrupted]
	#Enable feature.
	enabled = true
	#Show funny related gif in warning message.
	show_gif = true

#Settings of analysis feature.
#Analysing logs for most common reasons of crashes and displaying recommendations with fixes.
[analysis]
	#Enable feature.
	enabled = true
	#Here you can disable some Analysis by class names.
	#List of them can be found here: dev.kostromdan.mods.crash_assistant.app.logs_analyser.crash_reasons
	#For example "Create6Addons"
	blacklisted_reasons = []

#Checks crash_assistant compatibility with other incompatible mods.
#Highly unrecommended to disable!
[compatibility]
	#Enable feature.
	enabled = true

#You can customise GUI with this options.
[gui_customisation]
	#Append comment text with notice about sending screenshot of this gui tells nothing to modpack creators.
	show_dont_send_screenshot_of_gui_notice = true
	#Animate border to request user attention even more.
	screenshot_of_gui_notice_animated_border = true
	#You can make Upload All Button bigger/smaller to request user attention.
	#Default Swing font size is 12, Default for this button in crash assistant is 16.
	#Not recommended to set it more than 16, as it will affect the increase of GUI size because all text won't fit.
	upload_all_button_font_size = 16
	#Same as upload_all_button_font_size, but for Request Help button.
	request_help_button_font_size = 16
	#You can change Upload All Button color to request user attention.
	#format is "R_G_B", range is 0-255, for example "255_0_0" is red color. Use "default" to use default swing color.
	#Default for this button is "0_178_0" (dark green color).
	upload_all_button_foreground_color = "0_178_0"
	#Same as upload_all_button_foreground_color, but for Request Help button.
	#Default for this button is "0_0_178" (dark blue color).
	request_help_button_foreground_color = "0_0_178"

