
["Entity Temperature"]
	#List of entities that will insulate the player when riding them
	#A value of 0 provides no insulation; 1 provides full insulation
	#Format: [["entity_id", coldResistance, hotResistance], ["entity_id", coldResistance, hotResistance], etc...]
	"Insulated Mounts" = []
	#Defines temperature-emitting properties for entities
	#Format: [["entity_id", temperature, range, *units], ["entity_id", temperature, range, *units], etc...]
	#temperature: The temperature emitted by the entity
	#range: The range of the effect, in blocks
	#units: (Optional) The units of the temperature value (MC, F, or C). Defaults to MC
	"Entity Temperatures" = [["minecraft:blaze", 999, 1], ["minecraft:magma_cube", 0.5, 5], ["alexsmobs:froststalker", -0.2, 5], ["minecraft:elder_guardian", -0.2, 5], ["minecraft:snow_golem", -0.2, 5], ["minecraft:warden", -999, 3], ["blue_skies:armored_frost_spirit", -0.2, 3], ["blue_skies:crynocerous", -0.2, 3], ["blue_skies:crystal_camel", -0.2, 3], ["blue_skies:armored_frost_spirit", -0.2, 3], ["blue_skies:polargeist", -0.2, 3], ["blue_skies:sliv", 0.3, 3], ["blue_skies:firefly", 0.3, 3], ["blue_skies:emberback", 0.3, 3], ["endermanoverhaul:nether_wastes_enderman", 0.3, 3], ["endermanoverhaul:soulsand_valley_enderman", -0.2, 3], ["endermanoverhaul:snowy_enderman", -0.2, 3], ["endermanoverhaul:ice_spikes_enderman", -0.2, 3], ["creeperoverhaul:snowy_creeper", -0.2, 3], ["goety:haunt", -0.2, 3], ["goety:wraith", -0.2, 3], ["goety:border_wraith", -0.2, 3], ["goety:ice_golem", -0.3, 3], ["goety:inferno", 0.3, 3], ["aquamirae:tortured_soul", -0.2, 3], ["netherexp:wisp", -0.2, 3], ["netherexp:apparition", -0.3, 4], ["netherexp:ecto_slab", -0.1, 3], ["netherexp:banshee", -0.3, 5]]

["Fur Growth & Shedding"]
	#Defines how often a goat will try to grow its fur, the growth cooldown after shearing, and the chance of it succeeding
	#Format: [interval, cooldown, chance]
	"Goat Fur Growth Timings" = [1200, 2400, 0.2]
	#Defines how often a chameleon will try to shed its skin, the cooldown after shedding, and the chance of it succeeding
	#Format: [interval, cooldown, chance]
	"Chameleon Shedding Timings" = [100, 36000, 0.1]

["Mob Spawning"]
	#Defines the biomes that Chameleons can spawn in
	#Format: [["biome_id", weight], ["biome_id", weight], etc...]
	"Chameleon Spawn Biomes" = [["#c:is_hot/overworld", 5], ["#biomeswevegone:climate/hot", 5]]
	#Defines additional biomes that goats can spawn in
	#Format: [["biome_id", weight], ["biome_id", weight], etc...]
	#Not affected by the "Increase Goat Spawns" option
	"Goat Spawn Biomes" = []

