
#─────────────────────────────────────────────────────────────────────────
# Anywhere that uses item IDs also supports:
# • Tags (e.g. "#minecraft:planks")
# • Comma-separated lists (e.g. "minecraft:blaze_powder,#forge:rods/blaze")
#     Applies the setting to all listed IDs. Can use tags, regular IDs, and negation interchangeably
# • Negation (e.g. "!minecraft:black_dye")
#     Useful with lists/tags. Excludes the listed IDs from the setting
#     i.e. "#forge:dyes,!minecraft:black_dye" (all dyes EXCEPT black dye)
# Settings with "//v" will list elements vertically. Removing "//v" will list elements in one line
#─────────────────────────────────────────────────────────────────────────
#─────────────────────────────────────────────────────────────────────────
# Defines items that can be used as fuel
# └── Format: [["item_id", amount], ["item_id", amount], ...etc]
# • item_id: The item's ID (i.e. "minecraft:coal").
# • amount: The amount of fuel the item provides. Higher values mean the item burns longer
# ⌄ 
["Fuel Items"]
	#─────────────────────────────────//v
	Boiler = [
	    ["#minecraft:planks", 10],
	    ["minecraft:coal", 37],
	    ["minecraft:charcoal", 37],
	    ["#minecraft:logs_that_burn", 37],
	    ["minecraft:coal_block", 333],
	    ["minecraft:magma_block", 333],
	    ["minecraft:lava_bucket", 1000]
	]
	#─────────────────────────────────//v
	Icebox = [
	    ["minecraft:snowball", 10],
	    ["minecraft:clay_ball", 37],
	    ["minecraft:snow_block", 100],
	    ["minecraft:ice", 250],
	    ["minecraft:clay", 333],
	    ["minecraft:powder_snow_bucket", 100],
	    ["minecraft:packed_ice", 1000]
	]
	#─────────────────────────────────//v
	# (Negative values indicate cold fuel
	Hearth = [
	    ["#minecraft:planks", 10],
	    ["minecraft:coal", 37],
	    ["minecraft:charcoal", 37],
	    ["#minecraft:logs_that_burn", 37],
	    ["minecraft:coal_block", 333],
	    ["minecraft:magma_block", 333],
	    ["minecraft:lava_bucket", 1000],
	    ["minecraft:snowball", -10],
	    ["minecraft:clay_ball", -37],
	    ["minecraft:snow_block", -100],
	    ["minecraft:ice", -250],
	    ["minecraft:clay", -333],
	    ["minecraft:powder_snow_bucket", -100],
	    ["minecraft:packed_ice", -1000]
	]

["Soulspring Lamp"]
	#─────────────────────────────────────────────────────────────────────────//v
	# Defines items that the Soulspring Lamp can use as fuel
	# └── Format: [["item_id", amount], ["item_id", amount], ...etc]
	# • item_id: The item's ID (i.e. "cold_sweat:soul_sprout").
	# • amount: The amount of fuel the item provides. Higher values mean the item burns longer
	# ⌄ 
	"Fuel Items" = [
	    ["cold_sweat:soul_sprout", 4]
	]
	#─────────────────────────────────────────────────────────────────────────//v
	# Defines the dimensions that the Soulspring Lamp can be used in
	# └── Format: ["dimension_id", "dimension_id", ...etc]
	# ⌄ 
	"Valid Dimensions" = [
	    "minecraft:the_nether",
	    "blue_skies:everdawn"
	]

[Insulation]
	#─────────────────────────────────────────────────────────────────────────//v
	# Defines the items that can be used for insulating armor in the Sewing Table
	# ├── Format: [["item_id", cold, hot, *"static", *"{nbt}", *fillSlots], ["item_id", amount, adaptSpeed, "adaptive", *"{nbt}", *fillSlots], ...etc]
	# └── [* = optional]
	# • item_id: The item's ID (i.e. "minecraft:iron_ingot").
	# • cold: The cold insulation the item provides.
	# • hot: The heat insulation the item provides.
	# • amount: The amount of insulation the item provides.
	# • adaptSpeed: The speed at which the insulation adapts to the environment.
	# • *static/adaptive: The type of insulation the item provides. Defaults to "static" if unset
	# • *nbt: If set, the item will only provide insulation if it has the specified NBT tag.
	# • *fillSlots: If true, the item will fill 1 slot per 2 insulation points. Otherwise, the item will fill 1 slot.
	# ⌄ 
	"Insulation Ingredients" = [
	    ["cold_sweat:chameleon_molt", 4.0, 1.0, "adaptive", "", true],
	    ["alexsmobs:bear_fur", 2.0, 0.8, "adaptive", "", true],
	    ["blue_skies:fox_pelt", 1.0, 0.5, "adaptive", "", true],
	    ["alexsmobs:bison_fur", 2.0, 0.0, "static", "", true],
	    ["alexsmobs:kangaroo_hide", 0.0, 2.0, "static", "", true],
	    ["#minecraft:wool", 1.5, 0.0, "static", "", true],
	    ["cold_sweat:hoglin_hide", 0.0, 2.0, "static", "", true],
	    ["cold_sweat:goat_fur", 2.0, 0.0, "static", "", true],
	    ["#forge:leather", 1.0, 1.0, "static", "", true],
	    ["minecraft:rabbit_hide", 0.0, 1.5, "static", "", true],
	    ["netherdepthsupgrade:soul_sucker_leather", 0.0, 2.0, "static", "", true],
	    ["botania:manaweave_cloth", 1.0, 0.6, "adaptive", "", true],
	    ["irons_spellbooks:magic_cloth", 1.0, 0.6, "adaptive", "", true],
	    ["cold_sweat:chameleon_scale_helmet", 8, 0.0085, "adaptive", "", true],
	    ["cold_sweat:chameleon_scale_chestplate", 12, 0.0085, "adaptive", "", true],
	    ["cold_sweat:chameleon_scale_leggings", 10, 0.0085, "adaptive", "", true],
	    ["cold_sweat:chameleon_scale_boots", 8, 0.0085, "adaptive", "", true]
	]
	#─────────────────────────────────────────────────────────────────────────//v
	# Defines the items that provide insulation when worn
	# ** See Insulation Ingredients for formatting.
	# Enabling "fillSlots" will cause the armor's built-in insulation to consume the available insulation slots
	# i.e. if an item has 5 insulation slots and gives one slot of cold insulation by default, it will only have 4 free slots left
	# ⌄ 
	"Insulating Armor" = [
	    ["cold_sweat:goat_fur_cap", 8.0, 0.0, "static", "{}"],
	    ["cold_sweat:hoglin_tunic", 0.0, 12.0, "static", "{}"],
	    ["cold_sweat:hoglin_headpiece", 0.0, 8.0, "static", "{}"],
	    ["cold_sweat:goat_fur_pants", 10.0, 0.0, "static", "{}"],
	    ["minecraft:leather_chestplate", 6.0, 6.0, "static", "{}"],
	    ["cold_sweat:hoglin_hooves", 0.0, 8.0, "static", "{}"],
	    ["minecraft:leather_boots", 4.0, 4.0, "static", "{}"],
	    ["minecraft:leather_leggings", 5.0, 5.0, "static", "{}"],
	    ["cold_sweat:goat_fur_boots", 8.0, 0.0, "static", "{}"],
	    ["cold_sweat:hoglin_trousers", 0.0, 10.0, "static", "{}"],
	    ["cold_sweat:goat_fur_parka", 12.0, 0.0, "static", "{}"],
	    ["minecraft:leather_helmet", 4.0, 4.0, "static", "{}"],
	    ["netherdepthsupgrade:soul_sucker_boots", 0.0, 8.0, "static", "{}"],
	    ["cold_sweat:chameleon_scale_helmet", 8, 0.0085, "adaptive"],
	    ["cold_sweat:chameleon_scale_chestplate", 12, 0.0085, "adaptive"],
	    ["cold_sweat:chameleon_scale_leggings", 10, 0.0085, "adaptive"],
	    ["cold_sweat:chameleon_scale_boots", 8, 0.0085, "adaptive"]
	]
	#─────────────────────────────────────────────────────────────────────────//v
	# Defines the items that provide insulation when worn in a curio slot
	# See Insulation Ingredients for formatting. This setting does not have a "fillSlots" option
	# ⌄ 
	"Insulating Curios" = [
	    ["#curios:head", 1.0, 1.0, "static", "{}"],
	    ["#curios:body", 1.0, 1.0, "static", "{}"],
	    ["#curios:back", 1.0, 1.0, "static", "{}"],
	    ["#curios:feet", 1.0, 1.0, "static", "{}"],
	    ["irons_spellbooks:fireward_ring", 0.0, 20.0, "static", "{}"],
	    ["irons_spellbooks:frostward_ring", 20.0, 0.0, "static", "{}"],
	    ["irons_spellbooks:poisonward_ring", 10.0, 1.0, "adaptive", "{}"],
	    ["irons_spellbooks:invisibility_ring", 20.0, 1.0, "adaptive", "{}"]
	]
	#─────────────────────────────────────────────────────────────────────────
	# Defines how many insulation slots armor pieces have
	# There are 4 modes for this setting:
	# ┌ Static: Each armor slot (head, body, legs, feet) has a fixed number of insulation slots
	# └─── Format: [head, body, legs, feet]
	#      • head/body/legs/feet: The number of insulation slots for that armor slot
	# ┌ Linear: Number of slots increases steadily with protection
	# ├ Exponential: Number of slots increases rapidly with protection
	# ├ Logarithmic: Number of slots increases with protection, with diminishing returns
	# └─── Format: [multiplier, max-slots]
	#      • multiplier: Multiplied by the armor's protection value to get the number of insulation slots
	#      • max-slots: The maximum number of insulation slots an armor piece can have
	# ⌄ 
	"Insulation Slots" = ["static", 4, 6, 5, 4]
	#─────────────────────────────────────────────────────────────────────────
	# Defines the effectiveness of insulating items in protecting against temperature
	# ⌄ 
	#Range: 0.0 ~ Infinity
	"Insulation Strength" = 1.5
	#─────────────────────────────────────────────────────────────────────────//v
	# Defines wearable items that cannot be insulated
	# └── Format: ["item_id", "item_id", ...etc]
	# ⌄ 
	"Insulation Blacklist" = []
	#─────────────────────────────────────────────────────────────────────────//v
	# Allows for overriding the number of insulation slots for specific items
	# └── Format: [["item_id", slotCount, *"{nbt}"], ["item_id", slotCount, *"{nbt}"], ...etc]
	# • item_id: The item's ID (i.e. "minecraft:iron_helmet").
	# • slot_count: The number of insulation slots the item should have.
	# • *nbt: If set, the item will only have the specified number of insulation slots if it has the specified NBT tag.
	# ⌄ 
	"Insulation Slot Overrides" = []

[Consumables]
	#─────────────────────────────────────────────────────────────────────────//v
	# Defines items that affect the player's temperature when consumed
	# ├── Format: [["item_id", amount, *"{nbt}", *duration], ["item_id", amount, *"{nbt}", *duration], ...etc]
	# └── [* = optional]
	# • item_id: The item's ID (i.e. "minecraft:apple").
	# • amount: The amount to change the player's temperature by. Negative values are cold, positive values are hot
	# • *nbt: If set, the item will only affect the player's temperature if it has the specified NBT tag.
	# • *duration: If set, the player's temperature will remain increased/decreased for this amount of time (in ticks).
	# ⌄ 
	"Temperature-Affecting Foods" = [
	    ["cold_sweat:soul_sprout", -20.0, "{}", 1200]
	]
	#─────────────────────────────────────────────────────────────────────────
	# Defines how much a waterskin will change the player's body temperature when used
	# ⌄ 
	#Range: > 0
	"Waterskin Strength" = 50
	#─────────────────────────────────────────────────────────────────────────
	# Determines the strength of the Soulspring Lamp's effect before it is overwhelmed
	# A value of 1 means it will never be overwhelmed
	# ⌄ 
	#Range: 0.0 ~ 1.0
	"Soulspring Lamp Strength" = 0.6
	#─────────────────────────────────────────────────────────────────────────//v
	# Defines items that can be used to dry the player
	# └── Format: [["item_id", "turns_into"], ["item_id", "turns_into"], ...etc]
	# • item_id: The item's ID (i.e. "minecraft:sponge").
	# • turns_into: The item to be turned into when the item is used (i.e. "minecraft:wet_sponge").
	# ⌄ 
	"Drying Items" = [
	    ["minecraft:sponge", "minecraft:wet_sponge"]
	]
	#─────────────────────────────────────────────────────────────────────────
	# A multiplier for how effective a waterskin's over-time effect is, when held in the player's hotbar
	# ⌄ 
	#Range: 0.0 ~ Infinity
	"Waterskin Hotbar Strength" = 1.0
	#─────────────────────────────────────────────────────────────────────────
	# A multiplier for how quickly a waterskin will return to its neutral temperature when being used in the hotbar
	# ⌄ 
	#Range: 0.0 ~ Infinity
	"Waterskin Neutralize Speed" = 1.0

[Misc]
	#─────────────────────────────────────────────────────────────────────────//v
	# Defines items that affect the player's temperature when in the inventory
	# ├── Format: [["item_id", temperature, "slotRange", "trait", *"{nbt}", *maxEffect], ["item_id", temperature, "slotRange", "trait", *"{nbt}", *maxEffect], ...etc]
	# └── [* = optional]
	# • item_id: The item's ID (i.e. "minecraft:lava_bucket").
	# • temperature: The temperature change the item will apply to the entity. For core temperature, this is applied every tick
	# • slot_range: Either "inventory", "hotbar", or "hand". Defines what slots the item must be in to apply to the entity (inventory includes hotbar)
	# • trait: The temperature trait to apply the effect to. Typical values are "core" for body temperature or "world" for ambient temperature. More on the mod documentation page.
	# • *nbt: The NBT data the item must have to apply to the entity.
	# • *max_effect: The maximum temperature effect the item can apply to the entity.
	# ⌄ 
	"Carried Item Temperatures" = []

# Drains pressure from Create's netherite backtank if the player is in a hot/cold environment
# Triggered by the set bonus for wearing a full set of netherite diving gear
# Disabling these settings will not disable the heat/cold protection set bonus
# ⌄ 
["Create Backtank"]
	"Heat Drains Backtank" = true
	"Cold Drains Backtank" = false

["Item Functions"]
	#─────────────────────────────────────────────────────────────────────────
	# Allow fire resistance to block overheating damage
	# ⌄ 
	"Fire Resistance Immunity" = true
	#─────────────────────────────────────────────────────────────────────────
	# Allow ice resistance to block freezing damage
	# ⌄ 
	"Ice Resistance Immunity" = true
	#─────────────────────────────────────────────────────────────────────────
	# Whether a thermometer is required to see exact world and body temperature
	# ⌄ 
	"Require Thermometer" = true

["Hearth Extras"]
	#─────────────────────────────────────────────────────────────────────────//v
	# Potions containing any of these effects will not be allowed in the hearth
	# └── Format: ["effect_id", "effect_id", ...etc]
	# ⌄ 
	"Blacklisted Hearth Potions" = [
	    "minecraft:instant_damage",
	    "minecraft:poison",
	    "minecraft:wither",
	    "minecraft:weakness",
	    "minecraft:mining_fatigue",
	    "minecraft:slowness"
	]
	#─────────────────────────────────────────────────────────────────────────
	# If true, potions can be used in the hearth to give all players in range the potion effect
	# ⌄ 
	"Allow Potions in Hearth" = true

