
#Format: [["dimension_1", temperature1, *units], ["dimension_2", temperature2, *units]... etc]
#Common dimension IDs: minecraft:overworld, minecraft:the_nether, minecraft:the_end
[Dimensions]
	#Applies an offset to the world's temperature across an entire dimension
	"Dimension Temperature Offsets" = [["minecraft:the_nether", 0.3, "MC"], ["minecraft:the_end", -0.1, "MC"]]
	#Defines the temperature of a dimension, overriding all other biome and dimension temperatures/settings
	"Dimension Temperatures" = []

#Format: [["biome_1", <low-temp>, <high-temp>, <*units>], ["biome_2", <low-temp>, <high-temp>, <*units>]... etc]
#low-temp: The temperature of the biome at midnight
#high-temp: The temperature of the biome at noon
#units: Optional. The units of the temperature ("C" or "F". Defaults to MC units)
[Biomes]
	#Applies an offset to the temperature of a biome
	"Biome Temperature Offsets" = []
	#Defines the temperature of a biome, overriding the biome's default temperature
	"Biome Temperatures" = [["biomesoplenty:old_growth_woodland", 65.0, 78.0, "F"], ["biomesoplenty:grassland", 58.0, 82.0, "F"], ["terralith:amethyst_rainforest", 69.0, 84.0, "F"], ["biomesoplenty:bayou", 67.0, 78.0, "F"], ["terralith:volcanic_crater", 96.0, 162.0, "F"], ["terralith:cloud_forest", 38.0, 58.0, "F"], ["minecraft:deep_frozen_ocean", 56.0, 65.0, "F"], ["biomesoplenty:orchard", 58.0, 78.0, "F"], ["biomesoplenty:mediterranean_forest", 64.0, 78.0, "F"], ["terralith:moonlight_valley", 57.0, 76.0, "F"], ["biomesoplenty:origin_valley", 65.0, 80.0, "F"], ["biomesoplenty:seasonal_forest", 52.0, 64.0, "F"], ["terralith:sandstone_valley", 78.0, 114.0, "F"], ["biomesoplenty:volcano", 94.0, 120.0, "F"], ["terralith:temperate_highlands", 54.0, 80.0, "F"], ["minecraft:deep_dark", 63.0, 63.0, "F"], ["minecraft:old_growth_pine_taiga", 48.0, 62.0, "F"], ["biomesoplenty:coniferous_forest", 44.0, 58.0, "F"], ["minecraft:eroded_badlands", 88.0, 120.0, "F"], ["terralith:haze_mountain", 62.0, 74.0, "F"], ["biomesoplenty:wetland", 63.0, 74.0, "F"], ["biomesoplenty:forested_field", 64.0, 78.0, "F"], ["minecraft:old_growth_spruce_taiga", 48.0, 62.0, "F"], ["terralith:lavender_valley", 59.0, 76.0, "F"], ["minecraft:snowy_taiga", 19.0, 48.0, "F"], ["biomesoplenty:snowy_maple_woods", 32.0, 48.0, "F"], ["terralith:alpine_grove", 16.0, 53.0, "F"], ["biomesoplenty:lush_desert", 72.0, 94.0, "F"], ["biomesoplenty:dune_beach", 67.0, 78.0, "F"], ["terralith:shield", 48.0, 68.0, "F"], ["terralith:arid_highlands", 74.0, 102.0, "F"], ["biomesoplenty:ominous_woods", 65.0, 72.0, "F"], ["terralith:ancient_sands", 83.0, 130.0, "F"], ["terralith:lavender_forest", 56.0, 75.0, "F"], ["biomesoplenty:woodland", 67.0, 80.0, "F"], ["minecraft:wooded_badlands", 80.0, 108.0, "F"], ["biomesoplenty:dryland", 67.0, 97.0, "F"], ["minecraft:snowy_beach", 38.0, 52.0, "F"], ["biomesoplenty:bog", 62.0, 73.0, "F"], ["terralith:blooming_plateau", 49.0, 78.0, "F"], ["biomesoplenty:snowy_fir_clearing", 32.0, 51.0, "F"], ["biomesoplenty:snowy_coniferous_forest", 28.0, 48.0, "F"], ["minecraft:windswept_savanna", 67.0, 90.0, "F"], ["biomesoplenty:volcanic_plains", 82.0, 95.0, "F"], ["minecraft:swamp", 72.0, 84.0, "F"], ["terralith:yellowstone", 47.0, 68.0, "F"], ["biomesoplenty:maple_woods", 58.0, 68.0, "F"], ["biomesoplenty:jade_cliffs", 57.0, 70.0, "F"], ["terralith:basalt_cliffs", 76.0, 122.0, "F"], ["biomesoplenty:marsh", 76.0, 87.0, "F"], ["minecraft:taiga", 44.0, 62.0, "F"], ["minecraft:warm_ocean", 67.0, 76.0, "F"], ["biomesoplenty:pumpkin_patch", 57.0, 78.0, "F"], ["biomesoplenty:field", 64.0, 85.0, "F"], ["biomesoplenty:rocky_rainforest", 73.0, 86.0, "F"], ["terralith:savanna_badlands", 68.0, 99.0, "F"], ["minecraft:badlands", 84.0, 120.0, "F"], ["biomesoplenty:highland", 57.0, 70.0, "F"], ["terralith:steppe", 44.0, 78.0, "F"], ["minecraft:soul_sand_valley", 53.0, 53.0, "F"], ["terralith:caldera", 58.0, 71.0, "F"], ["minecraft:bamboo_jungle", 76.0, 87.0, "F"], ["biomesoplenty:fungal_jungle", 73.0, 86.0, "F"], ["terralith:granite_cliffs", 65.0, 85.0, "F"], ["terralith:brushland", 64.0, 89.0, "F"], ["minecraft:windswept_forest", 48.0, 66.0, "F"], ["terralith:rocky_mountains", 45.0, 73.0, "F"], ["minecraft:desert", 48.0, 115.0, "F"], ["terralith:fractured_savanna", 65.0, 92.0, "F"], ["biomesoplenty:clover_patch", 56.0, 78.0, "F"], ["minecraft:river", 60.0, 70.0, "F"], ["terralith:volcanic_peaks", 76.0, 122.0, "F"], ["terralith:birch_taiga", 40.0, 62.0, "F"], ["terralith:warped_mesa", 66.0, 84.0, "F"], ["terralith:highlands", 62.0, 74.0, "F"], ["terralith:desert_canyon", 73.0, 121.0, "F"], ["terralith:shield_clearing", 28.0, 80.0, "F"], ["terralith:forested_highlands", 43.0, 70.0, "F"], ["terralith:bryce_canyon", 72.0, 110.0, "F"], ["minecraft:frozen_peaks", 15.0, 33.0, "F"], ["minecraft:jungle", 76.0, 87.0, "F"], ["minecraft:snowy_slopes", 24.0, 38.0, "F"], ["minecraft:savanna_plateau", 76.0, 98.0, "F"], ["minecraft:old_growth_birch_forest", 58.0, 72.0, "F"], ["terralith:red_oasis", 58.0, 94.0, "F"], ["terralith:orchid_swamp", 62.0, 81.0, "F"], ["biomesoplenty:prairie", 66.0, 82.0, "F"], ["minecraft:stony_shore", 50.0, 64.0, "F"], ["biomesoplenty:mystic_grove", 65.0, 72.0, "F"], ["biomesoplenty:spider_nest", 75.0, 75.0, "F"], ["biomesoplenty:fir_clearing", 56.0, 68.0, "F"], ["terralith:desert_spires", 60.0, 121.0, "F"], ["minecraft:savanna", 70.0, 95.0, "F"]]

[Blocks]
	# Format:
	# [["block-ids", <temperature>, <range>, <*units>, <*max effect>, <*predicates>, <*nbt>, <*temperature-limit>], [etc...], [etc...]]
	# * = Optional
	# 
	# Arguments:
	# block-ids: Multiple IDs can be used by separating them with commas (i.e: "minecraft:torch,minecraft:wall_torch")
	# temperature: The temperature of the block, in Minecraft units
	# *falloff: The block is less effective as distance increases
	# *max effect: The maximum temperature change this block can cause to a player (even with multiple blocks)
	# *predicates: The state that the block has to be in for the temperature to be applied (i.e. lit=true).
	# - (Multiple predicates can be used by separating them with commas [i.e. "lit=true,waterlogged=false"])
	# *nbt: The NBT data that the block must have for the temperature to be applied.
	# *temperature-limit: The maximum world temperature at which this block temp will be effective.
	# - (Represents the minimum temp if the block temp is negative)
	"Block Temperatures" = [["cold_sweat:boiler", 0.27, 7, "mc", 0.88, "lit=true", "", 4], ["cold_sweat:icebox", -0.27, 7, "mc", 0.88, "frosted=true", "", 0], ["#minecraft:campfires", 0.476, 7, "mc", 0.9, "lit=true", " ", 8], ["minecraft:packed_ice,outer_end:glowing_ancient_ice,outer_end:glowing_ancient_ice_column,outer_end:glowing_ancient_ice_cap", -0.25, 4, "mc", 1.0, "", "", -0.7], ["minecraft:blue_ice,outer_end:ancient_ice,outer_end:ancient_ice_column,outer_end:ancient_ice_cap", -0.35, 4, "mc", 1.4, "", "", -0.7], ["#minecraft:ice,collectorsreap:lime_ice_cream_block,collectorsreap:pomegranate_ice_cream_block", -0.15, 4, "mc", 0.6, "", "", -0.7], ["netherexp:brazier_chest,botania:thermalily,botania:endoflame,botania:exoflame,minecraft:torchflower,blue_skies:blaze_bud", 0.2, 3, "mc", 0.8, "", "", 2], ["netherexp:soul_torchflower,blue_skies:frose,blue_skies:polar_posy,blue_skies:snowcap_mushroom,blue_skies:snowbloom", -0.2, 3, "mc", 0.8, "", "", -1], ["minecraft:fire,decorative_blocks:chandelier,respawnobelisks:radiant_flame,create_connected:fan_smoking_catalyst,nethersdelight:propelplant_torch,decorative_blocks:brazier,blue_skies:sunstone_block,", 0.476, 7, "mc", 0.9, "", "", 8], ["minecraft:soul_fire,decorative_blocks:soul_chandelier,goety:freezing_lamp,create_connected:fan_haunting_catalyst,create_connected:fan_freezing_catalyst,decorative_blocks:soul_brazier,blue_skies:moonstone_block", -0.476, 7, "mc", 0.9, "", "", -4], ["minecraft:soul_torch,blue_skies:moonstone_crystal", -0.15, 4, "mc", 1.0, "", "", -0.5], ["minecraft:jack_o_lantern,netherexp:ghoul_o_lantern,netherexp:burning_wither_skull_block,netherexp:burning_skull_block,minecraft:magma_block,netherexp:basaltic_geyser,undergarden:cloggrum_lantern,minecraft:lantern,blue_skies:brumble_lantern,scguns:plasma_lantern", 0.25, 4, "mc", 1.0], ["netherexp:soul_jack_o_lantern,netherexp:soul_ghoul_o_lantern,netherexp:soul_burning_wither_skull_block,netherexp:soul_burning_skull_block,netherexp:soul_magma_block,netherexp:souled_geyser,minecraft:soul_lantern,blue_skies:moonstone_lantern", -0.3, 4, "mc", 1.0, "", "", -1], ["minecraft:lava_cauldron,#create:fan_processing_catalysts/blasting,#forge:ores/uranium,immersiveengineering:sheetmetal_uranium,immersiveengineering:slab_sheetmetal_uranium", 0.5, 7, "mc", 1.5], ["immersiveengineering:storage_uranium,immersiveengineering:raw_block_uranium,immersiveengineering:slab_storage_uranium", 0.8, 5, "mc", 5]]
	#The maximum range of blocks' area of effect
	#Note: This will not change anything unless blocks are configured to utilize the expanded range
	#This value is capped at 16 for performance reasons
	#Range: 1 ~ 16
	"Block Range" = 7
	#When set to true, uses Cold Sweat's temperature system to determine water freezing behavior
	"Custom Freezing Behavior" = false
	#When set to true, modifies ice blocks to be harvestable with a pickaxe
	"Custom Ice Drops" = false

[Misc]
	#Overrides the world temperature when the player is within this structure
	#Format: [["structure_1", temperature1, *units], ["structure_2", temperature2, *units]... etc]
	#(* = optional)
	"Structure Temperatures" = [["minecraft:igloo", 65.0, "F"]]
	#Offsets the world temperature when the player is within this structure
	#Format: [["structure_1", offset1, *units], ["structure_2", offset2, *units]... etc]
	#(* = optional)
	"Structure Temperature Offsets" = []
	#List of blocks that will allow the player to sleep on them, regardless of the "Prevent Sleep When in Danger" setting
	#Use this list if the player is not getting the temperature effect from sleeping on particular blocks
	"Sleep Check Override Blocks" = ["#comforts:sleeping_bags"]
	#When set to true, players cannot sleep if they are cold or hot enough to die
	"Check Sleeping Conditions" = true
	#Converts damage dealt by Soul Fire to cold damage (default: true)
	#Does not affect the block's temperature
	"Cold Soul Fire" = true
	#A temperature offset applied when the sky is overcast
	#Format: [offset, *units]
	"Overcast Temperature Offset" = [-0.35, "mc"]

["Thermal Sources"]
	#How effective thermal sources are at normalizing temperature
	#Range: 0.0 ~ 1.0
	"Thermal Source Strength" = 0.75
	#List of additional blocks that thermal sources can spread through
	#Use this list if thermal sources aren't spreading through particular blocks that they should
	"Thermal Source Spread Whitelist" = ["minecraft:iron_bars", "minecraft:jungle_leaves", "minecraft:oak_leaves", "minecraft:spruce_leaves", "minecraft:dark_oak_leaves", "minecraft:acacia_leaves", "minecraft:birch_leaves", "minecraft:azalea_leaves", "minecraft:flowering_azalea_leaves", "minecraft:mangrove_leaves", "minecraft:cherry_leaves", "undergarden:smogstem_leaves", "undergarden:wigglewood_leaves", "undergarden:grongle_leaves", "outer_end:azure_leaves", "goety:rotten_leaves", "goety:windswept_leaves", "goety:pine_leaves", "goety:hardened_leaves", "blue_skies:bluebright_leaves", "blue_skies:starlit_leaves", "blue_skies:frostbright_leaves", "blue_skies:lunar_leaves", "blue_skies:dusk_leaves", "blue_skies:maple_leaves", "blue_skies:crystallized_leaves", "blue_skies:comet_leaves", "blue_skies:crescent_fruit_leaves", "create:encased_fluid_pipe"]
	#List of additional blocks that thermal sources spread through
	#Use this list if thermal sources are spreading through particular blocks that they shouldn't
	"Thermal Source Spread Blacklist" = []

	["Thermal Sources".Hearth]
		#Allows the hearth to automatically turn on/off based on nearby players' temperature
		#If false, it turns on/off by redstone signal instead
		"Automatic Hearth" = false
		#The distance the hearth's air will travel from a source, like the hearth itself or the end of a pipe
		#Range: > 0
		"Hearth Range" = 20
		#The maximum distance that air can be piped away from the hearth
		#Range: > 0
		"Max Hearth Range" = 96
		#The maximum volume of the hearth's area of effect
		#Range: > 1
		"Hearth Volume" = 12000
		#The time it takes for the hearth to be fully functional after being placed
		#Range: > 0
		"Hearth Warm-Up Time" = 1200
		#The maximum amount of insulation that the hearth can provide
		#Range: 0 ~ 10
		"Hearth Effect Strength" = 10
		#How often the hearth consumes fuel (in ticks)
		#Lower numbers mean fuel is consumed faster. Setting to 0 disables fuel consumption
		#Range: > 0
		"Hearth Fuel Consumption Interval" = 40

	["Thermal Sources".Boiler]
		#Allows the boiler to automatically turn on/off based on nearby players' temperature
		#If false, it turns on/off by redstone signal instead
		"Automatic Boiler" = false
		#The distance the boiler's air will travel from a source, like the boiler itself or the end of a pipe
		#Range: > 0
		"Boiler Range" = 16
		#The maximum distance that air can be piped away from the boiler
		#Range: > 0
		"Max Boiler Range" = 96
		#The maximum volume of the boiler's area of effect
		#Range: > 1
		"Boiler Volume" = 2000
		#The time it takes for the boiler to be fully functional after being placed
		#Range: > 0
		"Boiler Warm-Up Time" = 1200
		#The maximum amount of insulation that the boiler can provide
		#Range: 0 ~ 10
		"Boiler Warmth Strength" = 5
		#How often the boiler consumes fuel (in ticks)
		#Lower numbers mean fuel is consumed faster. Setting to 0 disables fuel consumption
		#Range: > 0
		"Boiler Fuel Consumption Interval" = 40

	["Thermal Sources".Icebox]
		#Allows the icebox to automatically turn on/off based on nearby players' temperature
		#If false, it turns on/off by redstone signal instead
		"Automatic Icebox" = false
		#The distance the icebox's air will travel from a source, like the icebox itself or the end of a pipe
		#Range: > 0
		"Icebox Range" = 16
		#The maximum distance that air can be piped away from the icebox
		#Range: > 0
		"Max Icebox Range" = 96
		#The maximum volume of the icebox's area of effect
		#Range: > 1
		"Icebox Volume" = 2000
		#The time it takes for the icebox to be fully functional after being placed
		#Range: > 0
		"Icebox Warm-Up Time" = 1200
		#The maximum amount of insulation that the icebox can provide
		#Range: 0 ~ 10
		"Icebox Chill Strength" = 5
		#How often the icebox consumes fuel (in ticks)
		#Lower numbers mean fuel is consumed faster. Setting to 0 disables fuel consumption
		#Range: > 0
		"Icebox Fuel Consumption Interval" = 40

