
[Villagers]
	#Wearing a Robe, along with variants, causes Villagers around the Player to have a negative Reputation unless said Player has 25 or more reputation among them, Default: false
	villagerHate = false
	#Wandering Traders transforms into Mavericks when struck by lightning, Default: true
	traderConvertMaverick = true
	#Villagers have a chance of converting into Warlocks if they're underneath a Block of Crying Obsidian, Default: true
	villagerConvertToWarlock = true
	#Villagers have a chance of converting into Heretics if they're near an active Nether Portal, Default: false
	villagerConvertToHeretic = false
	#Having an owned Ravaged or Ravager, causes Villagers around the Player to have a negative Reputation, Default: false
	villagerHateRavager = false
	#Casting Spell in the presence of Villagers will cause the Player to lose a number of Reputation, set 0 to disable, Default: 0
	#Range: > 0
	villagerHateSpells = 0

[Misc]
	#How many ticks it takes for Wights to spawn, Default: 24000
	#Range: > 0
	wightSpawnFreq = 24000
	#Spawn Chance for Wights spawning near the Player every Spawn Frequency, the lower the more likelier, Default: 10
	#Range: > 0
	wightSpawnChance = 10
	#Whether Goety Mobs can spawn in Overworld-like modded dimensions, Default: false
	interDimensionalMobs = false
	#Whether Wraiths should teleport towards their targets if they can't see them instead of just teleporting away when they're near them, Default: true
	wraithAggressiveTeleport = true
	#Whether Hellfire damage is mitigated by Fire Protection enchantment, Default: true
	hellfireFireProtection = true
	#Spawn Weight for Necromancer, Default: 1
	#Range: > 0
	necromancerSpawnWeight = 1
	#Whether undead mobs in the Crypts remain hostile even if players wear Necro Set, Default: true
	hostileCryptUndead = true
	#Spawn Weight for Wraith, Default: 20
	#Range: > 0
	wraithSpawnWeight = 20
	#Spawn Weight for Warlock, Default: 5
	#Range: > 0
	warlockSpawnWeight = 5
	#Whether Wights can spawn near players that have a high amount of Soul Energy, Default: true
	wightSpawn = true
	#Whether Mobs with Tall Heads(ie. Villagers, Illagers, etc.) will drop Tall Skulls, Default: true
	tallSkullDrop = true
	#Spawn Weight for Heretic, Default: 5
	#Range: > 0
	hereticSpawnWeight = 5
	#Whether Hellfire damage is halved on entities that are fire-immune, Default: true
	hellfireFireImmune = true
	#Spawn Weight for Maverick, Default: 5
	#Range: > 0
	maverickSpawnWeight = 5

	[Misc.Vizier]
		#Whether Viziers are persistent and do not naturally despawn. Default: false
		vizierPersistent = false
		#Viziers spawn Vexes instead of Irks, Default: false
		vizierMinion = false

	[Misc."Obsidian Monolith"]
		#Whether unowned Obsidian Monoliths, empowered by Heretics, converts nearby Overworld blocks to Nether blocks. Default: true
		obsidianMonolithSpread = true
		#Whether unowned Obsidian Monoliths, empowered by Heretics, change Overworld biomes to Nether biomes, Default: true
		obsidianMonolithBiome = true

	[Misc.Apostle]
		#Whether Apostles causes Villagers within 32 blocks of themselves to have a chance of converting into a Witch or Warlock. Default: true
		apostleConvertsVillagers = true
		#Whether Apostles causes entities within 32 blocks of themselves to take damage when in water. Default: true
		apostleBoilsWater = true
		#Gives Apostle an even more fancier death animation, Default: false
		fancierApostleDeath = false
		#Apostle spreads Nether biomes, and Nether Meteors deals environmental damage and spread Nether biomes as well. WARNING: Causes lots of lag. Default: false
		apocalypseMode = false
		#Whether Apostles are persistent and do not naturally despawn. Default: false
		apostlePersistent = true

[Servants]
	#Enable Redstone Cubes block detection mechanic, Default: true
	RedstoneCubeBlockFind = true
	#Mobs will automatically be hostile to servants, if servant is hostile towards the mob, Default: true
	mobSense = true
	#Owners can't attack or hurt their servants, Default: true
	ownerAttackCancel = true
	#Whether Servants or their owner are immune to attacks made by other servants that are summoned by the same owner, Default: true
	servantsMasterImmune = true
	#Maximum size Slime and Magma Cube Servants can obtain through Slime/Magma Block, Default: 4
	#Range: 1 ~ 127
	maxSlimeSize = 4
	#Whether Vex Servants can teleport to Players, Default: true
	vexTeleport = true
	#Whether Servants would naturally attack Witches or Warlocks if owner wears a full a robe that renders the former two neutral, Default: false
	variousRobeWitch = false
	#How many seconds it takes before Ravager can manually roar again, Default: 10
	#Range: > 0
	ravagerRoarCooldown = 10
	#Whether Servants can attack Creepers if Mob Griefing Rule is False, Default: true
	servantsAttackCreepers = true
	#How many seconds a servant can't heal through Soul Energy after being injured, Default: 5
	#Range: > 0
	servantHealHalt = 5
	#Whether Redstone Monstrosity breaks leaves and certain blocks if mob griefing is enabled, Default: true
	redstoneMonstrosityLeafBreak = true
	#Servants, when on staying mode, will load chunks around it, Default: true
	stayingServantChunkLoad = true
	#How far servants can patrol from their patrol location, Default: 16
	#Range: > 2
	servantPatrolRange = 16

	[Servants."Water Servants"]
		#How frequent Water Servants heal, count seconds, Default: 1
		#Range: > 0
		waterMinionHealTime = 1
		#Whether Water Servants can heal if summoned while wearing Abyss Robe, Default: true
		waterMinionHeal = true
		#How much Health Water Servants heal, numerically, Default: 1.0
		#Range: 0.0 ~ 1.7976931348623157E308
		waterMinionHealAmount = 1.0
		#How much Soul Energy it cost per second for a Water Servant to heal, Default: 1
		#Range: > 0
		waterMinionHealCost = 1

	[Servants."Nether Servants"]
		#How much Health Nether Servants heal, numerically, Default: 1.0
		#Range: 0.0 ~ 1.7976931348623157E308
		netherMinionHealAmount = 1.0
		#Whether Wildfire's summons have limited lifespans, Default: true
		wildfireSummonsLife = true
		#How frequent Nether Servants heal, count seconds, Default: 1
		#Range: > 0
		netherMinionHealTime = 1
		#How much Soul Energy it cost per second for a Nether Servant to heal, Default: 1
		#Range: > 0
		netherMinionHealCost = 1
		#Whether Nether Servants can heal if summoned while wearing Nether Robe, Default: true
		netherMinionHeal = true

	[Servants."Natural Servants"]
		#How much Health Natural Servants heal, numerically, Default: 1.0
		#Range: 0.0 ~ 1.7976931348623157E308
		naturalMinionHealAmount = 1.0
		#How frequent Natural Servants heal, count seconds, Default: 1
		#Range: > 0
		naturalMinionHealTime = 1
		#Whether Black Beasts gain buffs if total game time has gone long enough, Default: true
		blackBeastDayStrength = true
		#Whether owned Black Beasts drop Howling Soul, Default: true
		blackBeastHowlingSoul = true
		#Whether Natural Servants can heal if summoned while wearing Wild Robe, Default: true
		naturalMinionHeal = true
		#How much Soul Energy it cost per second for a Natural Servant to heal, Default: 1
		#Range: > 0
		naturalMinionHealCost = 1

	[Servants."Undead Servants"]
		#Whether Undead Servants burn in Sunlight if not wearing helmet, Default: true
		undeadServantSunlightBurn = true
		#Whether owned Necromancers drop Soul Jars, Default: true
		necromancerSoulJar = true
		#How frequent Undead Servants heal, count seconds, Default: 1
		#Range: > 0
		undeadServantsHealTime = 1
		#Whether Undead Servants can teleport to Players, Default: false
		undeadTeleport = false
		#Chance that a zombie (or subclass) servant is summoned as a baby, Default: 0.05
		#Range: 0.0 ~ 1.0
		zombieServantBabyChance = 0.05
		#Whether Servants would naturally attack Undead mobs if owner wears a full Necro Set, Default: false
		necroRobeUndead = false
		#Whether Necromancer's summons have limited lifespans, Default: true
		necromancerSummonsLife = true
		#Whether Undead Servants' helmet take damage when in Sunlight. Only takes effect if undeadServantSunlightBurn is enabled, Default: true
		undeadServantSunlightHelmet = true
		#How much Soul Energy it cost per second for an Undead Servant to heal, Default: 1
		#Range: > 0
		undeadServantsHealCost = 1
		#Whether Undead Servants can heal if summoned while wearing Necro Cape, Default: true
		undeadServantsHeal = true
		#How much Health Undead Servants heal, numerically, Default: 1.0
		#Range: 0.0 ~ 1.7976931348623157E308
		undeadServantsHealAmount = 1.0

	[Servants."Frost Servants"]
		#Whether Frost Servants can heal if summoned while wearing Frost Robe, Default: true
		frostMinionHeal = true
		#How much Soul Energy it cost per second for a Frost Servant to heal, Default: 1
		#Range: > 0
		frostMinionHealCost = 1
		#How much Health Frost Servants heal, numerically, Default: 1.0
		#Range: 0.0 ~ 1.7976931348623157E308
		frostMinionHealAmount = 1.0
		#How frequent Frost Servants heal, count seconds, Default: 1
		#Range: > 0
		frostMinionHealTime = 1

[Illagers]
	#Whether Enviokers, Inquillagers and Conquillagers can steal Totems of Souls or Totems of Undying, Default: true
	illagerSteal = true
	#Whether Sorcerers' max health increases the higher level they are, Default: true
	sorcererHPIncrease = true
	#Whether Illague Effect can spread from non Conquillagers that has the effect, Default: true
	illagueSpread = true
	#Whether Cryologers can summon Ice Chunks on Hard Difficulty, Default: false
	cryologerIceChunk = false

	[Illagers."Illager Assaults"]
		#How many Minecraft days of rest from Illager Assaults are added to Players killed by an Illager, Default: 2
		#Range: > 0
		illagerAssaultRestDeath = 2
		#How many ticks it takes for Illager Assaults to spawn, Default: 12000
		#Range: > 0
		illagerAssaultSpawnFreq = 12000
		#The maximum amount of Soul Energy the Player has that is taken consideration for the Assaults, Default: 30000
		#Range: > 0
		illagerAssaultLimit = 30000
		#How many Minecraft days of rest from Illager Assaults the Players have after killing a Minister, Default: 10
		#Range: > 0
		illagerAssaultRestMinister = 10
		#Spawn Chance for Illagers Hunting the Player every Spawn Frequency, the lower the more likelier, Default: 5
		#Range: > 0
		illagerAssaultSpawnChance = 5
		#Hitting the Illager Assault Limit of Soul Energy have a chance of giving Player Bad Omen effect, Default: true
		soulEnergyBadOmen = true
		#Modded Illagers Spawning based of Player's Soul Energy amount, Default: true
		illagerAssault = true
		#How much Soul Energy the Player has is required for Special Illagers to spawn, Default: 2500
		#Range: > 0
		illagerAssaultThreshold = 2500

	[Illagers.Raid]
		#Whether Modded Illagers appears in Raids, Default: true
		specialIllagerRaid = true
		#Whether Armored Ravagers spawn in Raids, Default: true
		armoredRavagerRaid = true

		[Illagers.Raid.Piker]
			#Whether Pikers appear in Raids, Default: true
			pikerRaid = true
			#How many Pikers each wave
			#Requires game restart
			#Must have no more and no less than 8 integers
			pikerRaidCount = [0, 0, 0, 2, 0, 3, 3, 5]

		[Illagers.Raid.Sorcerer]
			#Whether Sorcerers appear in Raids, Default: true
			sorcererRaid = true
			#How many Sorcerers each wave
			#Requires game restart
			#Must have no more and no less than 8 integers
			sorcererRaidCount = [0, 0, 1, 0, 1, 0, 1, 1]

		[Illagers.Raid."Hostile Redstone Golem"]
			#How many Hostile Redstone Golems each wave
			#Requires game restart
			#Must have no more and no less than 8 integers
			hostileRedstoneGolemRaidCount = [0, 0, 0, 0, 0, 1, 1, 0]
			#Whether Hostile Redstone Golems appear in Raids, Default: false
			hostileRedstoneGolemRaid = false

		[Illagers.Raid.Ripper]
			#Whether Rippers appear in Raids. They do not count as part of the Raid bar, Default: true
			ripperRaid = true
			#How many Rippers each wave
			#Requires game restart
			#Must have no more and no less than 8 integers
			ripperRaidCount = [0, 0, 0, 4, 0, 6, 6, 10]

		[Illagers.Raid.Inquillager]
			#How many Inquillagers each wave
			#Requires game restart
			#Must have no more and no less than 8 integers
			inquillagerRaidCount = [0, 0, 2, 0, 1, 2, 2, 3]
			#Whether Inquillagers appear in Raids, Default: true
			inquillagerRaid = true

		[Illagers.Raid.Warlock]
			#Whether Warlocks appear in Raids, Default: true
			warlockRaid = true
			#How many Warlocks each wave
			#Requires game restart
			#Must have no more and no less than 8 integers
			warlockRaidCount = [0, 0, 0, 0, 1, 2, 0, 1]

		[Illagers.Raid.Preacher]
			#Whether Preachers appear in Raids, Default: true
			preacherRaid = true
			#How many Preachers each wave
			#Requires game restart
			#Must have no more and no less than 8 integers
			preacherRaidCount = [0, 0, 1, 1, 0, 0, 0, 2]

		[Illagers.Raid.Envioker]
			#How many Enviokers each wave
			#Requires game restart
			#Must have no more and no less than 8 integers
			enviokerRaidCount = [0, 0, 0, 1, 0, 1, 1, 2]
			#Whether Enviokers appear in Raids, Default: true
			enviokerRaid = true

		[Illagers.Raid."Hostile Redstone Monstrosity"]
			#Whether Hostile Redstone Monstrosities appear in Raids, Default: false
			hostileRedstoneMonstrosityRaid = false
			#How many Hostile Redstone Monstrosities each wave
			#Requires game restart
			#Must have no more and no less than 8 integers
			hostileRedstoneMonstrosityRaidCount = [0, 0, 0, 0, 0, 0, 0, 1]

		[Illagers.Raid.Maverick]
			#How many Mavericks each wave
			#Requires game restart
			#Must have no more and no less than 8 integers
			maverickRaidCount = [0, 1, 0, 1, 0, 0, 0, 1]
			#Whether Mavericks appear in Raids, Default: true
			maverickRaid = true

		[Illagers.Raid."Storm Caster"]
			#Whether Storm Casters appear in Raids, Default: true
			stormCasterRaid = true
			#How many Storm Casters each wave
			#Requires game restart
			#Must have no more and no less than 8 integers
			stormCasterRaidCount = [0, 0, 0, 0, 1, 1, 0, 2]

		[Illagers.Raid.Crusher]
			#Whether Crushers appear in Raids, Default: true
			crusherRaid = true
			#How many Crushers each wave
			#Requires game restart
			#Must have no more and no less than 8 integers
			crusherRaidCount = [0, 0, 0, 0, 2, 2, 0, 2]

		[Illagers.Raid.Conquillager]
			#Whether Conquillagers appear in Raids, Default: true
			conquillagerRaid = true
			#How many Conquillagers each wave
			#Requires game restart
			#Must have no more and no less than 8 integers
			conquillagerRaidCount = [0, 4, 3, 3, 4, 4, 4, 2]

		[Illagers.Raid.Cryologer]
			#Whether Cryologers appear in Raids, Default: true
			cryologerRaid = true
			#How many Cryologers each wave
			#Requires game restart
			#Must have no more and no less than 8 integers
			cryologerRaidCount = [0, 0, 1, 1, 0, 0, 0, 2]

		[Illagers.Raid.Minister]
			#How many Ministers each wave
			#Requires game restart
			#Must have no more and no less than 8 integers
			ministerRaidCount = [0, 0, 0, 0, 0, 0, 0, 1]
			#Whether Ministers appear in Raids, Default: true
			ministerRaid = true

[Textures]
	#If certain mobs have a different texture during some holiday months, Default: true
	holidaySkins = true

	[Textures."Summoned Mobs"]

		[Textures."Summoned Mobs"."Wraith Servants"]
			#If Wraith Servants have custom textures, Default: true
			wraithServantTexture = true

		[Textures."Summoned Mobs"."Phantom Servants"]
			#If Phantom Servants have custom textures, Default: true
			phantomServantTexture = true
			#If Phantom Servants are translucent when upgraded, Default: true
			phantomServantTranslucent = true

		[Textures."Summoned Mobs"."Zombie Servants"]
			#If Jungle Zombie Servants have custom textures, Default: true
			jungleZombieServantTexture = true
			#If Husk Servants have custom textures, Default: true
			huskServantTexture = true
			#If Zombie Servants have custom textures, Default: true
			zombieServantTexture = true
			#If Drowned Servants have custom textures, Default: true
			drownedServantTexture = true
			#If Frozen Zombie Servants have custom textures, Default: true
			frozenZombieServantTexture = true

		[Textures."Summoned Mobs"."Slime Servants"]
			#If Crypt Slime Servants have custom textures, Default: true
			cryptSlimeServantTexture = true
			#If Magma Cube Servants have custom textures, Default: true
			magmaCubeServantTexture = true
			#If Slime Servants have custom textures, Default: true
			slimeServantTexture = true

		[Textures."Summoned Mobs"."Ghast Servants"]
			#If Ghast Servants have custom textures, Default: true
			ghastServantTexture = true

		[Textures."Summoned Mobs"."Spider Servants"]
			#If Spiders Servants have custom textures, Default: true
			spiderServantTexture = true
			#If Bone Spiders Servants have custom textures, Default: true
			boneSpiderServantTexture = true
			#If Cave Spiders Servants have custom textures, Default: true
			caveSpiderServantTexture = true

		[Textures."Summoned Mobs"."Wild Servants"]
			#If Poison-Quill Vine servants have custom textures, Default: true
			poisonQuillVineTexture = true
			#If Whisperer Servants have custom textures, Default: true
			whispererTexture = true
			#If Quick Growing Vine servants have custom textures, Default: true
			quickGrowingVineTexture = true
			#If Leapleaf Servants have custom textures, Default: true
			leapleafTexture = true

		[Textures."Summoned Mobs"."Blaze Servants"]
			#If Blaze Servants have custom textures, Default: true
			blazeServantTexture = true
			#If Wildfires have custom textures, Default: true
			wildfireTexture = true

		[Textures."Summoned Mobs"."Skeleton Servants"]
			#If Sunken Skeleton Servants have custom textures, Default: true
			sunkenSkeletonServantTexture = true
			#If Vanguard Servants have custom textures, Default: true
			vanguardServantTexture = true
			#If Skeleton Servants have custom textures, Default: true
			skeletonServantTexture = true
			#If Necromancer Servants have custom textures, Default: true
			necromancerServantTexture = true
			#If Wither Skeleton Servants have custom textures, Default: true
			witherSkeletonServantTexture = true
			#If Mossy Skeleton Servants have custom textures, Default: true
			mossySkeletonServantTexture = true
			#If Stray Servants have custom textures, Default: true
			strayServantTexture = true

		[Textures."Summoned Mobs".Vexes]
			#If Vexes have custom textures, Default: true
			vexTexture = true

		[Textures."Summoned Mobs"."Zombified Piglin Servants"]
			#If Zombified Piglin Servants have custom textures, Default: true
			zPiglinServantTexture = true

		[Textures."Summoned Mobs"."Redstone Golem"]
			#If Redstone Golems show cracks when damaged sufficiently, Default: true
			redstoneGolemCrack = true
			#If Redstone Golems have custom textures, Default: true
			redstoneGolemTexture = true

		[Textures."Summoned Mobs"."Redstone Monstrosity"]
			#If Redstone Monstrosities have custom textures, Default: true
			redstoneMonstrosityTexture = true

