
[stressValues]

	#.
	#Fine tune the kinetic stats of individual components
	[stressValues.v1]

		#.
		#.
		#[in Stress Units]
		#Configure the individual stress impact of mechanical blocks. Note that this cost is doubled for every speed increase it receives.
		[stressValues.v1.impact]
			copycat_cogwheel = 0.2
			copycat_large_cogwheel = 0.2
			copycat_shaft = 0.1

