#.
#The Speed of a Robo Bee in Blocks per Second. Default: 6
#Range: > 1
beeSpeed = 6
#.
#The Speed of the rotation of a Robo Bee in degrees per Second. Default: 45
#Range: > 1
beeRotationSpeed = 45
#.
#If true, the Robo Bee will be able to deliver packages from one port to another. Default: true
portToPort = true
#.
#The maximum distance a Robo Bee can travel. Default: -1 (unlimited)
#Range: > -1
beeMaxDistance = -1
#.
#If true, the Robo Bee will display a nametag with the address of the package it is carrying. Default: true
displayNametag = true
#.
#If true, when Spawning a Robo Bee with the Item it will take any Package from the offhand and deliver it. Default: true
allowRoboBeeSpawnPackageTransport = true

