
[item_pipe]

	[item_pipe.speed]
		#The speed at which items are transferred
		#A value of 1 means every tick
		#Range: > 1
		no_upgrade = 20
		#The speed at which items are transferred
		#A value of 1 means every tick
		#Range: > 1
		basic = 15
		#The speed at which items are transferred
		#A value of 1 means every tick
		#Range: > 1
		improved = 10
		#The speed at which items are transferred
		#A value of 1 means every tick
		#Range: > 1
		advanced = 5
		#The speed at which items are transferred
		#A value of 1 means every tick
		#Range: > 1
		ultimate = 1

	[item_pipe.amount]
		#The amount of items transferred
		#Range: > 1
		no_upgrade = 2
		#The amount of items transferred
		#Range: > 1
		basic = 4
		#The amount of items transferred
		#Range: > 1
		improved = 8
		#The amount of items transferred
		#Range: > 1
		advanced = 16
		#The amount of items transferred
		#Range: > 1
		ultimate = 32

[fluid_pipe]

	[fluid_pipe.amount]
		#The amount of mB transferred each tick
		#Range: > 1
		no_upgrade = 5
		#The amount of mB transferred each tick
		#Range: > 1
		basic = 20
		#The amount of mB transferred each tick
		#Range: > 1
		improved = 100
		#The amount of mB transferred each tick
		#Range: > 1
		advanced = 400
		#The amount of mB transferred each tick
		#Range: > 1
		ultimate = 1000

[energy_pipe]

	[energy_pipe.amount]
		#The amount of FE transferred each tick
		#Range: > 1
		no_upgrade = 256
		#The amount of FE transferred each tick
		#Range: > 1
		basic = 1024
		#The amount of FE transferred each tick
		#Range: > 1
		improved = 8192
		#The amount of FE transferred each tick
		#Range: > 1
		advanced = 32768
		#The amount of FE transferred each tick
		#Range: > 1
		ultimate = 131072

[gas_pipe]

	[gas_pipe.amount]
		#The amount of mB transferred each tick
		#Only available if Mekanism is installed
		#Range: > 1
		no_upgrade = 200
		#The amount of mB transferred each tick
		#Only available if Mekanism is installed
		#Range: > 1
		basic = 400
		#The amount of mB transferred each tick
		#Only available if Mekanism is installed
		#Range: > 1
		improved = 2000
		#The amount of mB transferred each tick
		#Only available if Mekanism is installed
		#Range: > 1
		advanced = 8000
		#The amount of mB transferred each tick
		#Only available if Mekanism is installed
		#Range: > 1
		ultimate = 40000

