
#Client settings
[client]
	#Should the numbed hearts obtained from being damaged when Tipsy flicker when you lose the effect and are about to take damage?
	numbedHeartFlickering = true
	#Should the food bar have a yellow overlay when the player has the Intoxication effect?
	intoxicationFoodOverlay = true
	#Should the chat scramble when the player has the Tipsy effect?
	scrambleChat = true
	#Should other player's nametags scramble when the player has the Tipsy effect?
	scrambleName = true
	#Should signs scramble when the player has the Tipsy effect?
	scrambleSign = true
	#Should kegs render the fluid texture in the background of the fluid slot?
	renderFluidInKeg = true

