
["Chimes Config"]
	#Toggle Wind Chime Animations
	Animations = true
	#Toggle falling Bamboo Leaf particles from Bamboo Wind Chimes
	"Bamboo Wind Chime Leaf Particles" = true
	#Toggle on/off pre 1.20 Bamboo Wind Chime textures
	"Previous Bamboo Wind Chime texture" = false

