
["Common Config"]
	#Capacity of Tools requiring Fluids in mB
	"Capacity of Tools requiring Fluids" = 200
	#Tool Capacity Enchantment Capacity Addition in mB
	"Capacity Addition of Tools with Capacity Enchantment" = 100
	#Canister Capacity in mB
	"Capacity of Canisters" = 4000
	#Canister Capacity Enchantment Capacity Addition in mB
	"Capacity Addition of Capacity Enchantment in Canisters" = 1000

