
#These configs are general configs that don't fit any other category.
[general]
	#Enable this and death counter messages will not show up in chat. This includes the leaderboard when manually querying with the command!
	hideDeathCounterMessages = false

