#Show how many more lines there are that currently don't fit the tooltip, just like the vanilla shulker box tooltip.
last_line = true
#Show black chat background behind tooltip lines for better visibility.
#Allowed Values: NONE, RECTANGLE, ADAPTIVE
background = "RECTANGLE"
#Amount of ticks the held item tooltip will be displayed for. Set to 0 to always display the tooltip as long as an item is being held.
#Range: > 0
display_time = 40
#Allow other mods to modify held item tooltip contents. Lines can be both added or changed.
additional_information = false
#Offset on x-axis from screen center.
#Range: > -2147483648
offset_x = 0
#Offset on y-axis from screen center.
#Range: > 0
offset_y = 59
#Interval in ticks after which the tooltip will be rebuilt. Some stats such as durability are rebuilt every tick regardless of this setting.
#Range: > 1
update_interval = 20
#Disables held item tooltips for specified items, mainly to prevent custom tooltips from overlapping.
#Format for every entry is "<namespace>:<path>". Tags are supported, must be in the format of "#<namespace>:<path>". Namespace may be omitted to use "minecraft" by default. May use asterisk as wildcard parameter via pattern matching, e.g. "minecraft:*_shulker_box" to match all shulker boxes no matter of color.
item_blacklist = []
#Scale of held item tooltips. Works together with "GUI Scale" option in "Video Settings". A smaller scale might make room for more rows.
#Range: 1 ~ 24
display_scale = 6
#Maximum amount of rows to be displayed for held item tooltips.
#Range: > 1
max_lines = 4

[components]

	#Amount of nbt tags on this item.
	[components.nbt_count]
		#Should this tooltip component be included when rendering held item tooltips.
		include = false
		#Priority for rendering this tooltip. When not enough lines are available (like an item with enchantments), components with a low priority will be skipped.
		#Range: > -2147483648
		priority = 10
		#Represent information for this component as if advanced tooltips were enabled independently of the actual setting.
		advanced_tooltips = false
		#The order in which this tooltip component appears in relation to other components. Smaller values appear first.
		#Range: > -2147483648
		ordering = 100
		#Should this tooltip component be hidden when vanilla's respective "HideFlags" property is set.
		respect_hide_flags = true

		#Text formatting settings for this component's text appearance.
		[components.nbt_count.formatting]
			#Should the text in this component appear bold.
			bold = false
			#Should the text in this component appear struck-through.
			strikethrough = false
			#The color of this component's text.
			#The color of this component's text.
			#Allowed Values: default, black, dark_blue, dark_green, dark_aqua, dark_red, dark_purple, gold, gray, dark_gray, blue, green, aqua, red, light_purple, yellow, white
			text_color = "gray"
			#Should the text in this component be replaced by random characters.
			obfuscated = false
			#Should the text in this component appear with an underline.
			underline = false
			#Should the text in this component appear italic.
			italic = false

	#A lore tag for this item, only present on custom items.
	[components.lore]
		#Should this tooltip component be included when rendering held item tooltips.
		include = true
		#Priority for rendering this tooltip. When not enough lines are available (like an item with enchantments), components with a low priority will be skipped.
		#Range: > -2147483648
		priority = 50
		#Represent information for this component as if advanced tooltips were enabled independently of the actual setting.
		advanced_tooltips = false
		#The order in which this tooltip component appears in relation to other components. Smaller values appear first.
		#Range: > -2147483648
		ordering = 50
		#Should this tooltip component be hidden when vanilla's respective "HideFlags" property is set.
		respect_hide_flags = true

		#Text formatting settings for this component's text appearance.
		[components.lore.formatting]
			#Should the text in this component appear bold.
			bold = false
			#Should the text in this component appear struck-through.
			strikethrough = false
			#The color of this component's text.
			#The color of this component's text.
			#Allowed Values: default, black, dark_blue, dark_green, dark_aqua, dark_red, dark_purple, gold, gray, dark_gray, blue, green, aqua, red, light_purple, yellow, white
			text_color = "default"
			#Should the text in this component be replaced by random characters.
			obfuscated = false
			#Should the text in this component appear with an underline.
			underline = false
			#Should the text in this component appear italic.
			italic = false

	#Additional information supplied by individual items such as potion effect and firework duration.
	[components.additional]
		#Should this tooltip component be included when rendering held item tooltips.
		include = true
		#Priority for rendering this tooltip. When not enough lines are available (like an item with enchantments), components with a low priority will be skipped.
		#Range: > -2147483648
		priority = 90
		#Represent information for this component as if advanced tooltips were enabled independently of the actual setting.
		advanced_tooltips = true
		#The order in which this tooltip component appears in relation to other components. Smaller values appear first.
		#Range: > -2147483648
		ordering = 20
		#Should this tooltip component be hidden when vanilla's respective "HideFlags" property is set.
		respect_hide_flags = true

		#Text formatting settings for this component's text appearance.
		[components.additional.formatting]
			#Should the text in this component appear bold.
			bold = false
			#Should the text in this component appear struck-through.
			strikethrough = false
			#The color of this component's text.
			#The color of this component's text.
			#Allowed Values: default, black, dark_blue, dark_green, dark_aqua, dark_red, dark_purple, gold, gray, dark_gray, blue, green, aqua, red, light_purple, yellow, white
			text_color = "default"
			#Should the text in this component be replaced by random characters.
			obfuscated = false
			#Should the text in this component appear with an underline.
			underline = false
			#Should the text in this component appear italic.
			italic = false

	#Durability of this item, only shown if the item is damageable and has been used.
	[components.durability]
		#Should this tooltip component be included when rendering held item tooltips.
		include = true
		#Priority for rendering this tooltip. When not enough lines are available (like an item with enchantments), components with a low priority will be skipped.
		#Range: > -2147483648
		priority = 80
		#Represent information for this component as if advanced tooltips were enabled independently of the actual setting.
		advanced_tooltips = false
		#The order in which this tooltip component appears in relation to other components. Smaller values appear first.
		#Range: > -2147483648
		ordering = 80
		#Should this tooltip component be hidden when vanilla's respective "HideFlags" property is set.
		respect_hide_flags = true

		#Text formatting settings for this component's text appearance.
		[components.durability.formatting]
			#Should the text in this component appear bold.
			bold = false
			#Should the text in this component appear struck-through.
			strikethrough = false
			#The color of this component's text.
			#The color of this component's text.
			#Allowed Values: default, black, dark_blue, dark_green, dark_aqua, dark_red, dark_purple, gold, gray, dark_gray, blue, green, aqua, red, light_purple, yellow, white
			text_color = "default"
			#Should the text in this component be replaced by random characters.
			obfuscated = false
			#Should the text in this component appear with an underline.
			underline = false
			#Should the text in this component appear italic.
			italic = false

	#Internal identifier of this item.
	[components.identifier]
		#Should this tooltip component be included when rendering held item tooltips.
		include = false
		#Priority for rendering this tooltip. When not enough lines are available (like an item with enchantments), components with a low priority will be skipped.
		#Range: > -2147483648
		priority = 20
		#Represent information for this component as if advanced tooltips were enabled independently of the actual setting.
		advanced_tooltips = false
		#The order in which this tooltip component appears in relation to other components. Smaller values appear first.
		#Range: > -2147483648
		ordering = 90
		#Should this tooltip component be hidden when vanilla's respective "HideFlags" property is set.
		respect_hide_flags = true

		#Text formatting settings for this component's text appearance.
		[components.identifier.formatting]
			#Should the text in this component appear bold.
			bold = false
			#Should the text in this component appear struck-through.
			strikethrough = false
			#The color of this component's text.
			#The color of this component's text.
			#Allowed Values: default, black, dark_blue, dark_green, dark_aqua, dark_red, dark_purple, gold, gray, dark_gray, blue, green, aqua, red, light_purple, yellow, white
			text_color = "gray"
			#Should the text in this component be replaced by random characters.
			obfuscated = false
			#Should the text in this component appear with an underline.
			underline = false
			#Should the text in this component appear italic.
			italic = false

	#Display name of the held item.
	[components.item_name]
		#Should this tooltip component be included when rendering held item tooltips.
		include = true
		#Priority for rendering this tooltip. When not enough lines are available (like an item with enchantments), components with a low priority will be skipped.
		#Range: > -2147483648
		priority = 100
		#Represent information for this component as if advanced tooltips were enabled independently of the actual setting.
		advanced_tooltips = false
		#The order in which this tooltip component appears in relation to other components. Smaller values appear first.
		#Range: > -2147483648
		ordering = 10
		#Should this tooltip component be hidden when vanilla's respective "HideFlags" property is set.
		respect_hide_flags = true

		#Text formatting settings for this component's text appearance.
		[components.item_name.formatting]
			#Should the text in this component appear bold.
			bold = false
			#Should the text in this component appear struck-through.
			strikethrough = false
			#The color of this component's text.
			#The color of this component's text.
			#Allowed Values: default, black, dark_blue, dark_green, dark_aqua, dark_red, dark_purple, gold, gray, dark_gray, blue, green, aqua, red, light_purple, yellow, white
			text_color = "default"
			#Should the text in this component be replaced by random characters.
			obfuscated = false
			#Should the text in this component appear with an underline.
			underline = false
			#Should the text in this component appear italic.
			italic = false

	#All enchantments on this item if any are present.
	[components.enchantments]
		#Should this tooltip component be included when rendering held item tooltips.
		include = true
		#Priority for rendering this tooltip. When not enough lines are available (like an item with enchantments), components with a low priority will be skipped.
		#Range: > -2147483648
		priority = 70
		#Represent information for this component as if advanced tooltips were enabled independently of the actual setting.
		advanced_tooltips = false
		#The order in which this tooltip component appears in relation to other components. Smaller values appear first.
		#Range: > -2147483648
		ordering = 30
		#Should this tooltip component be hidden when vanilla's respective "HideFlags" property is set.
		respect_hide_flags = true

		#Text formatting settings for this component's text appearance.
		[components.enchantments.formatting]
			#Should the text in this component appear bold.
			bold = false
			#Should the text in this component appear struck-through.
			strikethrough = false
			#The color of this component's text.
			#The color of this component's text.
			#Allowed Values: default, black, dark_blue, dark_green, dark_aqua, dark_red, dark_purple, gold, gray, dark_gray, blue, green, aqua, red, light_purple, yellow, white
			text_color = "default"
			#Should the text in this component be replaced by random characters.
			obfuscated = false
			#Should the text in this component appear with an underline.
			underline = false
			#Should the text in this component appear italic.
			italic = false

	#Attributes this item provides when used or equipped, like attack damage and armor protection.
	[components.modifiers]
		#Should this tooltip component be included when rendering held item tooltips.
		include = false
		#Priority for rendering this tooltip. When not enough lines are available (like an item with enchantments), components with a low priority will be skipped.
		#Range: > -2147483648
		priority = 30
		#Represent information for this component as if advanced tooltips were enabled independently of the actual setting.
		advanced_tooltips = false
		#The order in which this tooltip component appears in relation to other components. Smaller values appear first.
		#Range: > -2147483648
		ordering = 60
		#Should this tooltip component be hidden when vanilla's respective "HideFlags" property is set.
		respect_hide_flags = true

		#Text formatting settings for this component's text appearance.
		[components.modifiers.formatting]
			#Should the text in this component appear bold.
			bold = false
			#Should the text in this component appear struck-through.
			strikethrough = false
			#The color of this component's text.
			#The color of this component's text.
			#Allowed Values: default, black, dark_blue, dark_green, dark_aqua, dark_red, dark_purple, gold, gray, dark_gray, blue, green, aqua, red, light_purple, yellow, white
			text_color = "default"
			#Should the text in this component be replaced by random characters.
			obfuscated = false
			#Should the text in this component appear with an underline.
			underline = false
			#Should the text in this component appear italic.
			italic = false

	#Rendered when this item has the unbreakable tag giving it infinite durability.
	[components.unbreakable]
		#Should this tooltip component be included when rendering held item tooltips.
		include = true
		#Priority for rendering this tooltip. When not enough lines are available (like an item with enchantments), components with a low priority will be skipped.
		#Range: > -2147483648
		priority = 60
		#Represent information for this component as if advanced tooltips were enabled independently of the actual setting.
		advanced_tooltips = false
		#The order in which this tooltip component appears in relation to other components. Smaller values appear first.
		#Range: > -2147483648
		ordering = 70
		#Should this tooltip component be hidden when vanilla's respective "HideFlags" property is set.
		respect_hide_flags = true

		#Text formatting settings for this component's text appearance.
		[components.unbreakable.formatting]
			#Should the text in this component appear bold.
			bold = false
			#Should the text in this component appear struck-through.
			strikethrough = false
			#The color of this component's text.
			#The color of this component's text.
			#Allowed Values: default, black, dark_blue, dark_green, dark_aqua, dark_red, dark_purple, gold, gray, dark_gray, blue, green, aqua, red, light_purple, yellow, white
			text_color = "default"
			#Should the text in this component be replaced by random characters.
			obfuscated = false
			#Should the text in this component appear with an underline.
			underline = false
			#Should the text in this component appear italic.
			italic = false

	#The color of dyed items such a leather armor.
	[components.coloring]
		#Should this tooltip component be included when rendering held item tooltips.
		include = true
		#Priority for rendering this tooltip. When not enough lines are available (like an item with enchantments), components with a low priority will be skipped.
		#Range: > -2147483648
		priority = 40
		#Represent information for this component as if advanced tooltips were enabled independently of the actual setting.
		advanced_tooltips = true
		#The order in which this tooltip component appears in relation to other components. Smaller values appear first.
		#Range: > -2147483648
		ordering = 40
		#Should this tooltip component be hidden when vanilla's respective "HideFlags" property is set.
		respect_hide_flags = true

		#Text formatting settings for this component's text appearance.
		[components.coloring.formatting]
			#Should the text in this component appear bold.
			bold = false
			#Should the text in this component appear struck-through.
			strikethrough = false
			#The color of this component's text.
			#The color of this component's text.
			#Allowed Values: default, black, dark_blue, dark_green, dark_aqua, dark_red, dark_purple, gold, gray, dark_gray, blue, green, aqua, red, light_purple, yellow, white
			text_color = "default"
			#Should the text in this component be replaced by random characters.
			obfuscated = false
			#Should the text in this component appear with an underline.
			underline = false
			#Should the text in this component appear italic.
			italic = false

