
[animations]
	#Choose your preferred animation speed (1-15)
	#Range: 1.0 ~ 15.0
	animationSpeed = 8.0
	#Enable or disable swimming animation
	enableSwimmingAnimation = true
	#Swing animation speed (6-12)
	#Range: 6 ~ 12
	swingSpeed = 9
	#Enable or disable climb and crawl animation
	enableClimbAndCrawlAnimation = true
	#Enable or disable punching animation
	enablePunchingAnimation = true

[positions]
	#Viewmodel X Offset
	#Range: -10.0 ~ 10.0
	viewmodelXOffset = 0.0
	#Viewmodel Y Offset
	#Range: -10.0 ~ 10.0
	viewmodelYOffset = 0.0
	#Viewmodel Z Offset
	#Range: -10.0 ~ 10.0
	viewmodelZOffset = 0.0

[misc]
	#Enable MB3D compatibility mode
	mb3DCompat = false

[modRenderExclusions]
	#Mod IDs that should be excluded from custom rendering (entire mod).
	excludedModIds = ["pointblank", "jeg", "cataclysm"]
	#Specific item IDs to exclude from custom rendering (e.g. 'modid:itemname').
	excludedItemIds = []
	#Skips the blockItem renderer which is useful especially for create items cause their already 3d
	renderBlockAsItem = ["goety:haunted_lamp","goety:steep_lamp","create:cogwheel", "create:large_cogwheel", "create:shaft", "create:gearbox", "create:vertical_gearbox", "create:clutch", "create:gearshift", "create:encased_chain_drive", "create:adjustable_chain_gearshift", "create:belt_connector", "create:chain_conveyor", "create:creative_motor", "create:water_wheel", "create:large_water_wheel", "create:nozzle", "create:turntable", "create:hand_crank", "create:millstone", "create:crushing_wheel", "create:mechanical_press", "create:mechanical_mixer", "create:empty_blaze_burner", "create:blaze_burner", "create:depot", "create:weighted_ejector", "create:speedometer", "create:stressometer", "create:wooden_bracket", "create:metal_bracket", "create:schematicannon", "create:fluid_pipe", "create:mechanical_pump", "create:smart_fluid_pipe", "create:fluid_valve", "create:copper_valve_handle", "create:hose_pulley", "create:portable_fluid_interface", "create:steam_engine", "create:gantry_carriage", "create:gantry_shaft", "create:windmill_bearing", "create:mechanical_bearing", "create:clockwork_bearing", "create:rope_pulley", "create:elevator_pulley", "create:cart_assembler", "create:sticker", "create:contraption_controls", "create:mechanical_drill", "create:mechanical_saw", "create:deployer", "create:portable_storage_interface", "create:mechanical_harvester", "create:mechanical_plough", "create:mechanical_roller", "create:mechanical_crafter", "create:sequenced_gearshift", "create:flywheel", "create:rotation_speed_controller", "create:mechanical_arm", "create:controls", "create:andesite_funnel", "create:brass_funnel", "create:andesite_tunnel", "create:brass_tunnel", "create:package_frogport", "create:factory_gauge", "create:display_board", "create:peculiar_bell", "create:haunted_bell", "create:brown_toolbox", "create:clipboard"]

