#Range: > 0
ElectrolyzerBaseTickEnergy = 32
#Range: > 0
RotaryKilnBaseTickEnergy = 32
#Range: > 0
CarKilnBaseTickEnergy = 64
#Range: > 0
SteamTurbineGenerator = 1024
#Range: > 1
SteamTurbineSteam = 64
#Range: 0.0 ~ 96000.0
ElectrodeCost = 0.25
#Range: 0.0 ~ 2.147483647E9
CrucibleCooldownRate = 0.25
#Range: > 0
ChemicalReactorBaseTickEnergy = 32

