
#Block Settings
[blocks]
	#Nether vines have a random chance to grow their biomes' respective spores if they haven't reached maturity
	should_nether_vines_grow_spores = true
	#Fossil Ore that is covered on all faces slowly turns to Fossil Fuel
	renewable_fossil_fuel = true
	#How many seconds a geyser will go into cooldown for 
	#setting to "0" functionally disables the cooldown mechanic
	geyser_cooldown = 5
	#Defines how much vertical velocity you'll gain with a geyser
	#Range: 0.0 ~ 5.0
	geyser_push_velocity = 1.2
	#Defines how much vertical velocity you'll gain with a sporeshroom
	#Range: 0.0 ~ 5.0
	sporeshroom_push_velocity = 1.0
	#Unlocked Brazier Chests will refill loot after the specified time in seconds has elapsed
	#Range: 0 ~ 86400
	brazier_chest_refill_cooldown = 3600
	#Completed Treacherous Candles will become active again after the specified time in seconds has elapsed
	#Range: 0 ~ 86400
	treacherous_candle_completion_cooldown = 1800
	#If enabled frogmist blocks can be broken by hand otherwise it's hitbox only shows up when holding a hoe or frogmist in hand
	frogmist_breakable_by_fist = false
	#Stepping into Magma Cream Block will put you out if you're on fire
	magma_cream_block_douses_fire = true
	#How many bullets will be shot when a Shotgun Barrel is powered
	shotgun_barrel_bullets = 10
	#What causes Soul Magma Blocks to damage you 
	#SPRINTING - Only damages when sprinting on the block 
	#ALWAYS - Damages you unless sneaking 
	# 
	#Allowed Values: SPRINTING, ALWAYS
	soul_magma_damage_type = "SPRINTING"
	#How many seconds a Soul Swirl is in cooldown for when activated
	soul_swirls_cooldown = 50
	#How many seconds the player will be inflicted with Unbounded Speed when passing Soul Swirls
	unbounded_speed_duration = 10
	#What happens when Soul Swirls are bone mealed 
	#DROPS - Drops more of itself when bone mealed 
	#DUPLICATES - Places another soul swirl beside it 
	#DISABLED - Disables bone mealing soul swirls 
	# 
	#Allowed Values: DROPS, DUPLICATES, DISABLED
	soul_swirls_bone_meal_behavior = "DUPLICATES"
	#How much experience is dropped when treacherous flames are grinded down
	sculk_grinder_experience = 450

#Item Settings
[items]
	#The stack size for all Potions & Antidotes 
	#Vanilla value is "1"
	#Range: 1 ~ 64
	potion_stack_size = 16
	#Caps the Maximum Damage of the Jackhammer-Fist to this value
	will_o_wisp_stack_size = 40.0
	#The amount of time Black Icicle deal Freezing Damage when shot or skewered
	black_icicle_freeze_ticks = 500

#Entity Settings
[entities]
	#Blazes get dimmer as their health decreases like in Minecraft Dungeons
	diminishing_blazes = true
	#Magma Cube texture changes depending on it's size so that it's no longer mixels 
	#The New Textures used are from FaithFul 32x and 64x respectively
	pixel_consistent_magma_cubes = true
	#Skeletons when killed fossilize soul soil blocks underneath into Fossil Ore
	skeleton_fossilization = true
	#Wither Skeletons when killed fossilize soul soil blocks underneath into Fossil Fuel Ore
	wither_skeleton_fossilization = true
	#Mobs will be scared to pathfind through Soul Glass
	phasmophobic_mobs = true
	#Hoglins will drop hogham instead of porkchops
	hoglin_drops_hogham = true
	#Wither Skeletons will drop fossil fuel instead of coal
	wither_skeleton_drops_fossil_fuel = false
	#Defines 1 in specified chance for how often wisps emerge from ecto soul sand blocks
	wisp_emerging_chance = 50
	#Wisps will turn the soul sand they emerged from into Suspicious Soul Sand
	suspicious_soul_sand_from_wisp_emerging = true
	#Defines how ecto slabs will emerge from soul swirls 
	#ALWAYS - has a chance to emerge whenever passed through 
	#UNBOUNDED_SPEED_ONLY - can emerge only if inflicted with unbounded speed 
	#NEVER - never emerges from soul swirls 
	# 
	#Allowed Values: ALWAYS, UNBOUNDED_SPEED_ONLY, NEVER
	ecto_slab_emerging_behavior = "UNBOUNDED_SPEED_ONLY"
	#Defines 1 in specified chance for how often Ecto Slabs emerge from soul swirls 
	ecto_slab_emerging_chance = 40
	#Defines 1 in specified chance for how often Ecto Slabs emerge from soul swirls if the player has Unbounded Speed
	ecto_slab_emerging_with_unbounded_speed = 10

#Game Mechanic Settings
[game_mechanics]
	#Changes how close the nether fog is to the player 
	#VANILLA - Fog caps at 12 chunks 
	#MEDIUM - Changes with render distance 
	#FAR - Behaves like Medium but with even greater distance 
	#DISABLED - Turns off the nether fog 
	# 
	#Allowed Values: VANILLA, MEDIUM, FAR, DISABLED
	nether_fog_distance = "MEDIUM"
	#Increases the size of all nether biomes, great for experiencing the new biome overhauls 
	#WARNING: this setting has to be enabled before you generate a new world 
	#once enabled in a world it cannot be disabled without deleting DIM-1 in the world folder
	larger_nether_biomes = false
	#Defines if Immunity Effect duration reduction is scaled by the incoming effect amplifier
	amplifier_immunity_reduction = true
	#Ectoplasm will rust all nearby plated netherite blocks it comes in contact with
	ectoplasm_rusts_netherite = true
	#Ectoplasm slowly starts dealing freezing damage when in contact
	ectoplasm_freezing_damage = true
	#Soul Sand movement speed reduction will be less intrusive when enabled
	reduce_soul_sand_slowness = false
	#Soul Speed will no longer damage your boots when enabled
	remove_soul_speed_durability_penalty = false
	#Developer Mode enables various Loggers and other technical information for debugging sake 
	#If you aren't a dev or someone with technical knowledge then keep it at "false" lol
	dev_test_mode = false

#Sub-Biome Settings
[sub_biome]
	#Enables Secondary & Tertiary Sub-Biomes
	enable_sub_biomes = true
	#How often Black Ice Glaciers should replace Soul Sand Valley
	#Range: 0.0 ~ 1.0
	black_ice_glaciers_rarity = 0.075
	#How big Black Ice Glaciers should be
	black_ice_glaciers_size = 64

#Particle & Sound Settings
[particles_and_sounds]
	#Fireballs will leave a trail of fire behind
	improved_fireball_particles = true
	#Soul Fire will emit unique particles instead of smoke
	improved_soul_fire_particles = true
	#Black will produce aerosol particles
	enable_black_ice_particles = true
	#Ectoplasm will produce light rays and rising particles
	enable_ectoplasm_particles = true
	#Ectoplasm will occasionally produce whispering sounds
	enable_ectoplasm_sounds = true

