#.
#Slow down a ponder scene whenever there is text on screen.
comfyReading = false
#.
#Show additional info in the ponder view and reload scene scripts more frequently.
editingMode = false

#.
#Settings for the Placement Assist
[placementAssist]
	#.
	#What indicator should be used when showing where the assisted placement ends up relative to your crosshair
	#Choose 'NONE' to disable the Indicator altogether
	#Allowed Values: TEXTURE, TRIANGLE, NONE
	indicatorType = "TEXTURE"
	#.
	#Change the size of the Indicator by this multiplier
	#Range: 0.0 ~ 3.4028234663852886E38
	indicatorScale = 1.0

