
["Combustion Reactor"]
	#The time interval consumed each time: time>-11
	time = 0.0

["Brass plates"]
	Armor = 2.0
	Toughness = 1.0
	Weight = 2.0

["Iron plates"]
	Armor = 1.0
	Toughness = 0.0
	Weight = 1.0

["Alloy plates"]
	Armor = 2.0
	Toughness = 1.0
	Weight = 1.5

