
["JEI/REI"]
	#Water Evaporation category will be shown in JEI/REI. 
	#*Will be disabled automatically if evaporation is disabled or salt:heaters tag has no blocks.
	JeiWaterEvaporationEnabled = true
	#Growing Salt Crystals category will be shown in JEI/REI.
	#*Will be disabled automatically if Growing Crystals is disabled.
	JeiGrowingSaltCrystalsEnabled = true

[Compatibility]
	#Overlay texture will be drawn over salted foods. Disable if there's an issue with rendering items.
	SaltingOverlayEnabled = true

