
[miscellaneous]
	# If true, foods indicate in their tooltips the last time they've been eaten, and their current diversity contribution.
	#
	isFoodTooltipEnabled = true
	#
	# If true, the food book lists benefits that you haven't acquired yet, in addition to the ones you have.
	#
	#
	shouldShowInactiveBenefits = true

