[general]
giveJournal = false
holdToCast = true
showUnread = true
showToasts = true
defaultLineColor = false
hideUnknownFishNames = true
rodDurabilityMultiplier = 1.0
crateWeight = 6
crateQuality = 1
[minigame]
doMinigame = true
doFeedback = true
doSuccessSound = true
doFailSound = true
minigameDifficulty = 1.0
[worldgen]
disableFishingBoat = false
