[general]
giveJournal = false
holdToCast = true
doMinigame = true
showUnread = true
showToasts = true
minigameDifficulty = 1.0
rodDurabilityMultiplier = 1.0
defaultLineColor = false
hideUnknownFishNames = true
[worldgen]
disableFishingBoat = false
