
#To return to the vanilla /enchant command (in case of mod incompatibilities), make sure all settings in this category are disabled.
[enchant_command]
	#Remove the max level limit from the /enchant command, this allows any enchantment to be applied with a level of 1-255.
	remove_max_level_limit = true
	#Allow overriding and removing (by setting the level to 0) existing enchantment levels via the /enchant command.
	#Additionally makes enchanting books work via the command.
	fix_enchant_command = true

