#Any level of feather falling prevents farmland being trampled.
no_farmland_trample = true
#Looting also affects dropped experience points.
looting_boosts_xp = true
#Infinity enchantment no longer requires a single arrow to be present in the player inventory.
true_infinity = true
#Disables damage immunity when hit by a projectile. Makes it possible for entities to be hit by multiple projectiles at once (mainly useful for the multishot enchantment).
no_projectile_immunity = true
#Mending no longer repairs items using xp.
#Instead mending allows the item to be repaired in the crafting menu in the same way as in an anvil without any experience cost: combining a tool with another one or the appropriate repair item is possible, all enchantments will be preserved (but no new ones from the item repaired with will be added as an anvil would do).
#Additionally, repairing items enchanted with mending (only repairing, no renaming or adding more enchantments) in an anvil doesn't increase the items repair cost any further.
mending_crafting_repair = false
#Allow all kinds of horse armor to be enchanted directly in the enchanting table.
#Disabling this will still allow for applying enchantments in an anvil, that needs to be disabled per enchantment in the custom .json configs.
enchantable_horse_armor = true
#Allow shields to be enchanted directly in the enchanting table.
#Disabling this will still allow for applying enchantments in an anvil, that needs to be disabled per enchantment in the custom .json configs.
enchantable_shields = true
#Enchanting a few modded items (e.g. Farmer's Delight's skillet) is broken by the changes this mod makes to how enchantments may be applied to items. This option enables a patch for Forge itself to help better support such items.
allow_mod_item_support = true

