
#General settings
[general]
	#
	#debugLog (default:false)
	#Enable debug log.
	debugLog = false
	#
	#dispBothLanguagesOnTooltip (default:true)
	#Item names will be displayed in both languages to the item tooltip.
	dispBothLanguagesOnTooltip = true
	#
	#dispBothLanguagesOnJade (default:true)
	#Item names will be displayed in both languages to the Jade tooltip.
	dispBothLanguagesOnJade = true
	#
	#replaceItemNames (default:false)
	#If true, primary language is sub-language (default is English).
	#Item names are strictly replaced with the sub-language in any case.
	#If false, primary language is your selected language.
	#Sub-language (default is English) is simply added to the second line of the tooltip.
	replaceItemNames = false
	#
	#subLanguage (default:en_us)
	#Sub-language for item names.
	subLanguage = "en_us"
	#
	#subLangOn1stLine (default:false)
	#Sub-language is displayed on 1st line of tooltip.
	#This option is available if dispBothLanguagesOnTooltip is true.
	subLangOn1stLine = false

