
#.
#Client/server settings
[common]
	#.
	#Defines default Belt Grinder appearance
	#Range: 0 ~ 4
	defaultBeltGrinderSkin = 0
	#.
	#You can insert and extract from the Centrifuge while it is working.
	easyCentrifuge = false

