
["YUNG's Cave Biomes"]

	["YUNG's Cave Biomes"."Lost Caves"]
		"Enable Sandstorms" = true
		"Min Sandstorm Duration (seconds)" = 120
		"Max Sandstorm Duration (seconds)" = 600
		"Min Time Between Sandstorms (seconds)" = 1200
		"Max Time Between Sandstorms (seconds)" = 2400
		"Render Extra Particles During Sandstorms" = true

		["YUNG's Cave Biomes"."Lost Caves"."Biome Noise Parameters"]
			#Range: -1.0 ~ 1.0
			"Temperature Min" = 0.55
			#Range: -1.0 ~ 1.0
			"Temperature Max" = 1.0
			#Range: -1.0 ~ 1.0
			"Humidity Min" = -1.0
			#Range: -1.0 ~ 1.0
			"Humidity Max" = 0.6
			#Range: -1.0 ~ 1.0
			"Continentalness Min" = 0.3
			#Range: -1.0 ~ 1.0
			"Continentalness Max" = 1.0
			#Range: -1.0 ~ 1.0
			"Erosion Min" = -1.0
			#Range: -1.0 ~ 1.0
			"Erosion Max" = 1.0
			#Range: 0.0 ~ 1.0
			"Depth Min" = 0.2
			#Range: 0.0 ~ 1.0
			"Depth Max" = 0.9
			#Range: -1.0 ~ 1.0
			"Weirdness Min" = -1.0
			#Range: -1.0 ~ 1.0
			"Weirdness Max" = 1.0
			#Range: -1.0 ~ 1.0
			Offset = 0.0

	["YUNG's Cave Biomes"."Frosted Caves"]

		["YUNG's Cave Biomes"."Frosted Caves"."Biome Noise Parameters"]
			#Range: -1.0 ~ 1.0
			"Temperature Min" = -1.0
			#Range: -1.0 ~ 1.0
			"Temperature Max" = -0.7
			#Range: -1.0 ~ 1.0
			"Humidity Min" = -1.0
			#Range: -1.0 ~ 1.0
			"Humidity Max" = 1.0
			#Range: -1.0 ~ 1.0
			"Continentalness Min" = -0.19
			#Range: -1.0 ~ 1.0
			"Continentalness Max" = 1.0
			#Range: -1.0 ~ 1.0
			"Erosion Min" = -1.0
			#Range: -1.0 ~ 1.0
			"Erosion Max" = 1.0
			#Range: 0.0 ~ 1.0
			"Depth Min" = 0.2
			#Range: 0.0 ~ 1.0
			"Depth Max" = 0.9
			#Range: -1.0 ~ 1.0
			"Weirdness Min" = -1.0
			#Range: -1.0 ~ 1.0
			"Weirdness Max" = 1.0
			#Range: -1.0 ~ 1.0
			Offset = 0.0

	["YUNG's Cave Biomes".Other]

		["YUNG's Cave Biomes".Other."Vanilla Biome Modifications"]

			["YUNG's Cave Biomes".Other."Vanilla Biome Modifications"."Dripstone Caves"]
				#Range: -1.0 ~ 1.0
				"Temperature Min" = -0.7
				#Range: -1.0 ~ 1.0
				"Temperature Max" = 1.0
				#Range: -1.0 ~ 1.0
				"Humidity Min" = -1.0
				#Range: -1.0 ~ 1.0
				"Humidity Max" = 1.0
				#Range: -1.0 ~ 1.0
				"Continentalness Min" = 0.8
				#Range: -1.0 ~ 1.0
				"Continentalness Max" = 1.0
				#Range: -1.0 ~ 1.0
				"Erosion Min" = -1.0
				#Range: -1.0 ~ 1.0
				"Erosion Max" = 1.0
				#Range: 0.0 ~ 1.0
				"Depth Min" = 0.2
				#Range: 0.0 ~ 1.0
				"Depth Max" = 0.9
				#Range: -1.0 ~ 1.0
				"Weirdness Min" = -1.0
				#Range: -1.0 ~ 1.0
				"Weirdness Max" = 1.0
				#Range: -1.0 ~ 1.0
				Offset = 0.0

