
[General]
	renderThreeBoltHelmetOverlay = true
	stylizedBossbar = true

[IceMazeAmbient]
	spawnParticles = true
	playAmbientSounds = true
	playBiomeMusic = true
	playCorneliaMusic = true

